package main

var Polynomials map[string]Polynomial = map[string]Polynomial{
	"270-600/12V": Polynomial{
		Gain:                    0.01,
		ApproximationType:       "MACLAURIN",
		FrequencyLowerBound:     0.0,
		FrequencyUpperBound:     0.0,
		ApproximationLowerBound: 600.0,
		ApproximationUpperBound: 1100.0,
		MaximumError:            0.0,
	},
	"270-600/24V": Polynomial{
		Gain:                    0.01,
		ApproximationType:       "MACLAURIN",
		FrequencyLowerBound:     0.0,
		FrequencyUpperBound:     0.0,
		ApproximationLowerBound: 600.0,
		ApproximationUpperBound: 1100.0,
		MaximumError:            0.0,
	},
	"270-800/12V": Polynomial{
		Gain:                    0.016666666666666666,
		ApproximationType:       "MACLAURIN",
		FrequencyLowerBound:     0.0,
		FrequencyUpperBound:     0.0,
		ApproximationLowerBound: 800.0,
		ApproximationUpperBound: 1100.0,
		MaximumError:            0.0,
	},
	"Druck PTX-1830-A": Polynomial{
		Gain:                    0.0008,
		ApproximationType:       "MACLAURIN",
		FrequencyLowerBound:     0.0,
		FrequencyUpperBound:     0.0,
		ApproximationLowerBound: 0.0,
		ApproximationUpperBound: 20.0,
		MaximumError:            0.0,
	},
	"Druck PTX-1830-B": Polynomial{
		Gain:                    250.0,
		ApproximationType:       "MACLAURIN",
		FrequencyLowerBound:     0.0,
		FrequencyUpperBound:     0.0,
		ApproximationLowerBound: 0.004,
		ApproximationUpperBound: 0.02,
		MaximumError:            0.0,
	},
	"InfraBSU microphone": Polynomial{
		Gain:                    0.008,
		ApproximationType:       "MACLAURIN",
		FrequencyLowerBound:     0.0,
		FrequencyUpperBound:     0.0,
		ApproximationLowerBound: 0.0,
		ApproximationUpperBound: 0.0,
		MaximumError:            0.0,
		Notes:                   &[]string{"this is incorrect, enough to get a plot\nin theory this is linear with +/- 10mV for +/- 125Pa (1.25 mbar)\n which translates to +/- 1V for +/- 125mbar\n"}[0],
	},
	"LM35": Polynomial{
		Gain:                    0.01,
		ApproximationType:       "MACLAURIN",
		FrequencyLowerBound:     0.0,
		FrequencyUpperBound:     0.0,
		ApproximationLowerBound: -55.0,
		ApproximationUpperBound: 150.0,
		MaximumError:            0.0,
	},
	"SEAWATER": Polynomial{
		Gain:                    1.03,
		ApproximationType:       "MACLAURIN",
		FrequencyLowerBound:     0.0,
		FrequencyUpperBound:     0.0,
		ApproximationLowerBound: 0.0,
		ApproximationUpperBound: 20.0,
		MaximumError:            0.0,
	},
}
