package main

var Responses []Response = []Response{

	// Borehole Sensors
	Response{

		Sensors: []Sensor{
			Sensor{
				Sensors:  []string{"2 Hz Duke Malin Seismometer"},
				Filters:  []string{"2_Hz_Duke_Malin_Seismometer"},
				Channels: "Z12",
				Reversed: true,
			},
		},

		Dataloggers: []Datalogger{
			Datalogger{
				Dataloggers:   []string{"Q330S/3", "Q330S/6"},
				Type:          "CG",
				Label:         "EH",
				Rate:          100.0,
				Frequency:     15.0,
				StorageFormat: "Steim2",
				ClockDrift:    0.0001,
				Filters:       []string{"Q330S+_FLbelow100-100-PREAMP32"},
			},
			Datalogger{
				Dataloggers:   []string{"Q330/3", "Q330/6"},
				Type:          "CG",
				Label:         "EH",
				Rate:          100.0,
				Frequency:     15.0,
				StorageFormat: "Steim2",
				ClockDrift:    0.0001,
				Filters:       []string{"Q330_FLbelow100-100-PREAMP"},
			},
		},
	},

	// Short Period Sensors
	Response{
		Sensors: []Sensor{
			Sensor{
				Sensors:  []string{"L4C"},
				Filters:  []string{"L4C"},
				Channels: "Z",
				Reversed: false,
			},

			Sensor{
				Sensors:  []string{"L4C-3D"},
				Filters:  []string{"L4C"},
				Channels: "ZNE",
				Reversed: false,
			},
			Sensor{
				Sensors:  []string{"LE-3Dlite"},
				Filters:  []string{"LE-3Dlite"},
				Channels: "ZNE",
				Reversed: false,
			},
			Sensor{
				Sensors:  []string{"LE-3DliteMkII"},
				Filters:  []string{"LE-3DliteMkII"},
				Channels: "ZNE",
				Reversed: false,
			},
		},

		Dataloggers: []Datalogger{
			Datalogger{
				Dataloggers:   []string{"Q330/3", "Q330/6"},
				Type:          "CG",
				Label:         "EH",
				Rate:          100.0,
				Frequency:     15.0,
				StorageFormat: "Steim2",
				ClockDrift:    0.0001,
				Filters:       []string{"Q330_FLbelow100-100"},
				Skip:          "KQ03",
			},
			Datalogger{
				Dataloggers:   []string{"Q330/3", "Q330/6"},
				Type:          "CG",
				Label:         "EH",
				Rate:          200.0,
				Frequency:     15.0,
				StorageFormat: "Steim2",
				ClockDrift:    0.0001,
				Filters:       []string{"Q330_FLbelow100-200"},
				Match:         "KQ03",
			},
			Datalogger{
				Dataloggers:   []string{"Q330S/3", "Q330S/6"},
				Type:          "CG",
				Label:         "EH",
				Rate:          100.0,
				Frequency:     15.0,
				StorageFormat: "Steim2",
				ClockDrift:    0.0001,
				Filters:       []string{"Q330S+_FLbelow100-100"},
				Skip:          "KQ03",
			},
			Datalogger{
				Dataloggers:   []string{"Q4120/6"},
				Type:          "CG",
				Label:         "EH",
				Rate:          100.0,
				Frequency:     1.0,
				StorageFormat: "Steim2",
				ClockDrift:    0.0001,
				Filters:       []string{"Q4120-100"},
			},
			/*
				Datalogger{
					Dataloggers:   []string{"EARSS/3"},
					Type:          "TG",
					Label:         "EH",
					Rate:          50.0,
					Frequency:     15.0,
					StorageFormat: "Steim2",
					ClockDrift:    0.0001,
					Filters:       []string{"EARSS-50"},
				},
			*/
			Datalogger{
				Dataloggers:   []string{"Taurus"},
				Type:          "CG",
				Label:         "EH",
				Rate:          100.0,
				Frequency:     15,
				StorageFormat: "Steim2",
				ClockDrift:    0.0001,
				Filters:       []string{"Taurus-100"},
			},
		},
	},

	// Broadband Sensors

	// STS-2
	Response{
		Sensors: []Sensor{
			Sensor{
				Sensors:  []string{"STS-2"},
				Filters:  []string{"STS-2"},
				Channels: "ZNE",
			},
		},
		Dataloggers: []Datalogger{
			Datalogger{
				Dataloggers:   []string{"Q330HR/6"},
				Type:          "CG",
				Label:         "HH",
				Rate:          100.0,
				Frequency:     1.0,
				StorageFormat: "Steim2",
				ClockDrift:    0.0001,
				Filters:       []string{"Q330HR_FLbelow100-100"},
			},
			Datalogger{
				Dataloggers:   []string{"Q330HR/6"},
				Type:          "CG",
				Label:         "LH",
				Rate:          1.0,
				Frequency:     0.1,
				StorageFormat: "Steim2",
				ClockDrift:    0.0001,
				Filters:       []string{"Q330HR_FLbelow100-1"},
			},
			Datalogger{
				Dataloggers:   []string{"Q330HR/6"},
				Type:          "CG",
				Label:         "VH",
				Rate:          0.1,
				Frequency:     0.05,
				StorageFormat: "Steim2",
				ClockDrift:    0.0001,
				Filters:       []string{"Q330HR_FLbelow100-0.1"},
			},
			Datalogger{
				Dataloggers:   []string{"Q4120/6"},
				Type:          "CG",
				Label:         "HH",
				Rate:          100.0,
				Frequency:     1.0,
				StorageFormat: "Steim2",
				ClockDrift:    0.0001,
				Filters:       []string{"Q4120-100"},
				Reversed:      true,
			},
			Datalogger{
				Dataloggers:   []string{"Q4120/6"},
				Type:          "CG",
				Label:         "LH",
				Rate:          1.0,
				Frequency:     0.1,
				StorageFormat: "Steim2",
				ClockDrift:    0.0001,
				Filters:       []string{"Q4120-1"},
				Reversed:      true,
			},
			Datalogger{
				Dataloggers:   []string{"Q4120/6"},
				Type:          "CG",
				Label:         "VH",
				Rate:          0.1,
				Frequency:     0.05,
				StorageFormat: "Steim2",
				ClockDrift:    0.0001,
				Filters:       []string{"Q4120-0.1"},
				Reversed:      true,
			},
		},
	},

	Response{
		Sensors: []Sensor{
			Sensor{
				Sensors:  []string{"Nanometrics Trillium 120QA"},
				Filters:  []string{"TRILLIUM-120QA"},
				Channels: "ZNE",
				Reversed: false,
			},
			Sensor{
				Sensors:  []string{"CMG-3TB-GN"},
				Filters:  []string{"CMG-3TB-GN"},
				Channels: "Z12",
				Reversed: false,
			},
			Sensor{
				Sensors:  []string{"CMG-3ESPC", "CMG-3ESP"},
				Filters:  []string{"CMG-3ESP-GN"},
				Channels: "ZNE",
				Reversed: false,
			},
			Sensor{
				Sensors:  []string{"CMG-40T-30S"},
				Filters:  []string{"CMG-40T-30S-GNS"},
				Channels: "ZNE",
				Reversed: false,
			},
			Sensor{
				Sensors:  []string{"CMG-40T-60S"},
				Filters:  []string{"CMG-40T-60S-GN"},
				Channels: "ZNE",
				Reversed: false,
			},
		},

		Dataloggers: []Datalogger{
			Datalogger{
				Dataloggers:   []string{"Q330/3", "Q330/6"},
				Type:          "CG",
				Label:         "HH",
				Rate:          100.0,
				Frequency:     1.0,
				StorageFormat: "Steim2",
				ClockDrift:    0.0001,
				Filters:       []string{"Q330_FLbelow100-100"},
			},
			Datalogger{
				Dataloggers:   []string{"Q330/3", "Q330/6"},
				Type:          "CG",
				Label:         "LH",
				Rate:          1.0,
				Frequency:     0.1,
				StorageFormat: "Steim2",
				ClockDrift:    0.0001,
				Filters:       []string{"Q330_FLbelow100-1"},
			},
			Datalogger{
				Dataloggers:   []string{"Q330/3", "Q330/6"},
				Type:          "CG",
				Label:         "VH",
				Rate:          0.1,
				Frequency:     0.05,
				StorageFormat: "Steim2",
				ClockDrift:    0.0001,
				Filters:       []string{"Q330_FLbelow100-0.1"},
			},
			Datalogger{
				Dataloggers:   []string{"Q330S/3", "Q330S/6"},
				Type:          "CG",
				Label:         "HH",
				Rate:          100.0,
				Frequency:     1.0,
				StorageFormat: "Steim2",
				ClockDrift:    0.0001,
				Filters:       []string{"Q330S+_FLbelow100-100"},
			},
			Datalogger{
				Dataloggers:   []string{"Q330S/3", "Q330S/6"},
				Type:          "CG",
				Label:         "LH",
				Rate:          1.0,
				Frequency:     0.1,
				StorageFormat: "Steim2",
				ClockDrift:    0.0001,
				Filters:       []string{"Q330S+_FLbelow100-1"},
			},
			Datalogger{
				Dataloggers:   []string{"Q330S/3", "Q330S/6"},
				Type:          "CG",
				Label:         "VH",
				Rate:          0.1,
				Frequency:     0.05,
				StorageFormat: "Steim2",
				ClockDrift:    0.0001,
				Filters:       []string{"Q330S+_FLbelow100-0.1"},
			},
			Datalogger{
				Dataloggers:   []string{"Q4120/6", "Q730/4"},
				Type:          "CG",
				Label:         "VH",
				Rate:          0.1,
				Frequency:     0.05,
				StorageFormat: "Steim2",
				ClockDrift:    0.0001,
				Filters:       []string{"Q4120-0.1"},
			},
			Datalogger{
				Dataloggers:   []string{"Q4120/6", "Q730/4"},
				Type:          "CG",
				Label:         "HH",
				Rate:          100.0,
				Frequency:     1.0,
				StorageFormat: "Steim2",
				ClockDrift:    0.0001,
				Filters:       []string{"Q4120-100"},
			},
			Datalogger{
				Dataloggers:   []string{"Q730/4"},
				Type:          "CG",
				Label:         "BH",
				Rate:          40.0,
				Frequency:     1.0,
				StorageFormat: "Steim2",
				ClockDrift:    0.0001,
				Filters:       []string{"Q4120-40"},
				Match:         "FWVZ",
			},
			Datalogger{
				Dataloggers:   []string{"Q4120/6", "Q730/4"},
				Type:          "CG",
				Label:         "LH",
				Rate:          1.0,
				Frequency:     0.1,
				StorageFormat: "Steim2",
				ClockDrift:    0.0001,
				Filters:       []string{"Q4120-1"},
			},
			Datalogger{
				Dataloggers:   []string{"ORION"},
				Type:          "CG",
				Label:         "HH",
				Rate:          100.0,
				Frequency:     1,
				StorageFormat: "Steim2",
				ClockDrift:    0.0001,
				Filters:       []string{"ORION-100"},
			},
		},
	},

	// Strong Motion Sensors
	Response{
		Sensors: []Sensor{
			Sensor{
				Sensors:  []string{"FBA-ES-T", "FBA-ES-T-ISO"},
				Filters:  []string{"FBA-ES-T"},
				Channels: "ZNE",
			},
		},
		Dataloggers: []Datalogger{
			Datalogger{
				Dataloggers:   []string{"Q330S/6"},
				Type:          "TG",
				Label:         "HN",
				Rate:          200.0,
				Frequency:     1.0,
				StorageFormat: "Steim2",
				ClockDrift:    0.0001,
				Filters:       []string{"Q330S+_FLbelow100-200"},
			},
			Datalogger{
				Dataloggers:   []string{"Q330S/6"},
				Type:          "CG",
				Label:         "BN",
				Rate:          50.0,
				Frequency:     1.0,
				StorageFormat: "Steim2",
				ClockDrift:    0.0001,
				Filters:       []string{"Q330S+_FLbelow100-50"},
			},
			Datalogger{
				Dataloggers:   []string{"Q330S/6"},
				Type:          "CG",
				Label:         "LN",
				Rate:          1.0,
				Frequency:     0.1,
				StorageFormat: "Steim2",
				ClockDrift:    0.0001,
				Filters:       []string{"Q330S+_FLbelow100-1"},
			},
			/*
				Datalogger{
					Dataloggers:   []string{"Q330/3", "Q330/6"},
					Type:          "TG",
					Label:         "HN",
					Rate:          200.0,
					Frequency:     1.0,
					StorageFormat: "Steim2",
					ClockDrift:    0.0001,
					Filters:       []string{"Q330_FLbelow100-200"},
				},
			*/
			Datalogger{
				Dataloggers:   []string{"Q330/6", "Q330HR/6"},
				Type:          "TG",
				Label:         "HN",
				Rate:          200.0,
				Frequency:     1.0,
				StorageFormat: "Steim2",
				ClockDrift:    0.0001,
				Filters:       []string{"Q330_FLbelow100-200"},
			},
			Datalogger{
				Dataloggers:   []string{"Q330/6", "Q330HR/6"},
				Type:          "CG",
				Label:         "BN",
				Rate:          50,
				Frequency:     1,
				StorageFormat: "Steim2",
				ClockDrift:    0.0001,
				Filters:       []string{"Q330_FLbelow100-50"},
			},
			Datalogger{
				Dataloggers:   []string{"Q330/6", "Q330HR/6"},
				Type:          "CG",
				Label:         "LN",
				Rate:          1,
				Frequency:     0.1,
				StorageFormat: "Steim2",
				ClockDrift:    0.0001,
				Filters:       []string{"Q330_FLbelow100-1"},
			},

			Datalogger{
				Dataloggers:   []string{"Q4120/6"},
				Type:          "TG",
				Label:         "HN",
				Rate:          200.0,
				Frequency:     1.0,
				StorageFormat: "Steim2",
				ClockDrift:    0.0001,
				Filters:       []string{"Q4120-200"},
				Reversed:      true,
			},
			/*
				Datalogger{
					Dataloggers:   []string{"Q4120/6"},
					Type:          "CG",
					Label:         "BN",
					Rate:          50,
					Frequency:     1,
					StorageFormat: "Steim2",
					ClockDrift:    0.0001,
					Filters:       []string{"Q4120-50"},
					Reversed:      true,
				},
			*/
			Datalogger{
				Dataloggers:   []string{"Q4120/6"},
				Type:          "CG",
				Label:         "LN",
				Rate:          1.0,
				Frequency:     0.1,
				StorageFormat: "Steim2",
				ClockDrift:    0.0001,
				Filters:       []string{"Q4120-1"},
				Reversed:      true,
			},
			/*
				Datalogger{
					Dataloggers:   []string{"Obsidian 4X Datalogger"},
					Type:          "CG",
					Label:         "LN",
					Rate:          1.0,
					Frequency:     0.1,
					StorageFormat: "Steim2",
					ClockDrift:    0.0001,
					Filters:       []string{"BASALT-1"},
				},
			*/
		},
	},

	// Strong Motion Recorders
	Response{

		Sensors: []Sensor{
			Sensor{
				Sensors:  []string{"FBA-23-DECK"},
				Filters:  []string{"FBA-23-DECK"},
				Channels: "1Z2",
				Reversed: true,
			},
			Sensor{
				Sensors:  []string{"FBA-ES-T-DECK"},
				Filters:  []string{"FBA-ES-T-DECK"},
				Channels: "ENZ",
				Reversed: false,
				Match:    "^[A-Z][A-Z][A-Z]$",
				Skip:     "^DCZ$",
			},
			Sensor{
				Sensors:  []string{"FBA-ES-T-DECK"},
				Filters:  []string{"FBA-ES-T-DECK"},
				Channels: "21Z",
				Reversed: false,
				Match:    "^DCZ$",
			},
			Sensor{
				Sensors:  []string{"FBA-ES-T-DECK"},
				Filters:  []string{"FBA-ES-T-DECK"},
				Channels: "21Z",
				Reversed: false,
				Skip:     "^[A-Z][A-Z][A-Z]$",
			},
			Sensor{
				Sensors:  []string{"FBA-ES-T-BASALT"},
				Filters:  []string{"FBA-ES-T-BASALT"},
				Channels: "ZNE",
				Match:    "^[A-Z][A-Z][A-Z]$",
				Reversed: false,
			},
			Sensor{
				Sensors:  []string{"FBA-ES-T-BASALT"},
				Filters:  []string{"FBA-ES-T-BASALT"},
				Channels: "Z12",
				Skip:     "^[A-Z][A-Z][A-Z]$",
				Reversed: false,
			},
			Sensor{
				Sensors:  []string{"FBA-ES-T-OBSIDIAN"},
				Filters:  []string{"FBA-ES-T-BASALT"},
				Channels: "Z12",
				Skip:     "^[A-Z][A-Z][A-Z]$",
				Reversed: false,
			},
			Sensor{
				Sensors:  []string{"CUSP3D"},
				Filters:  []string{"CUSP SENSOR"},
				Channels: "21Z",
			},
			Sensor{
				Sensors:  []string{"CUSP3C"},
				Filters:  []string{"CUSP SENSOR"},
				Channels: "21Z",
			},
			Sensor{
				Sensors:  []string{"CUSP3B"},
				Filters:  []string{"CUSP SENSOR"},
				Channels: "21Z",
			},
			Sensor{
				Sensors:  []string{"CUSP3A"},
				Filters:  []string{"CUSP SENSOR"},
				Channels: "21Z",
			},
		},

		Dataloggers: []Datalogger{
			Datalogger{
				Dataloggers:   []string{"OBSIDIAN"},
				Type:          "TG",
				Label:         "HN",
				Rate:          200.0,
				Frequency:     1.0,
				StorageFormat: "Steim2",
				ClockDrift:    0.0001,
				Filters:       []string{"BASALT-200"},
			},
			Datalogger{
				Dataloggers:   []string{"OBSIDIAN"},
				Type:          "CG",
				Label:         "BN",
				Rate:          50.0,
				Frequency:     1.0,
				StorageFormat: "Steim2",
				ClockDrift:    0.0001,
				Filters:       []string{"BASALT-50"},
			},
			Datalogger{
				Dataloggers:   []string{"BASALT"},
				Type:          "TG",
				Label:         "HN",
				Rate:          200.0,
				Frequency:     1.0,
				StorageFormat: "Steim2",
				ClockDrift:    0.0001,
				Filters:       []string{"BASALT-200"},
			},

			Datalogger{
				Dataloggers:   []string{"BASALT"},
				Type:          "CG",
				Label:         "BN",
				Rate:          50.0,
				Frequency:     1.0,
				StorageFormat: "Steim2",
				ClockDrift:    0.0001,
				Filters:       []string{"BASALT-50"},
			},

			Datalogger{
				Dataloggers:   []string{"ETNA", "K2"},
				Type:          "TG",
				Label:         "HN",
				Rate:          200.0,
				Frequency:     1.0,
				StorageFormat: "Steim2",
				ClockDrift:    0.0001,
				Filters:       []string{"ALTUS-200"},
			},

			Datalogger{
				Dataloggers:   []string{"CUSP3D", "CUSP3C"},
				Type:          "TG",
				Label:         "HN",
				Rate:          200.0,
				Frequency:     1.0,
				StorageFormat: "Steim2",
				ClockDrift:    0.0001,
				Filters:       []string{"CUSP-200"},
			},
			Datalogger{
				Dataloggers:   []string{"CUSP3D", "CUSP3C"},
				Type:          "CG",
				Label:         "BN",
				Rate:          50.0,
				Frequency:     1.0,
				StorageFormat: "Steim2",
				ClockDrift:    0.0001,
				Filters:       []string{"CUSP-50"},
			},
			Datalogger{
				Dataloggers:   []string{"CUSP3A", "CUSP3B"},
				Type:          "TG",
				Label:         "HN",
				Rate:          200.0,
				Frequency:     1.0,
				StorageFormat: "Steim2",
				ClockDrift:    0.0001,
				Filters:       []string{"CUSP-200"},
			},
		},
	},

	// Barometers
	Response{
		Sensors: []Sensor{
			Sensor{
				Sensors:  []string{"270-600/12V"},
				Filters:  []string{"270-600/12V"},
				Channels: "F",
				Reversed: false,
			},
			Sensor{
				Sensors:  []string{"270-600/24V"},
				Filters:  []string{"270-600/24V"},
				Channels: "F",
				Reversed: false,
			},
			Sensor{
				Sensors:  []string{"270-800/12V"},
				Filters:  []string{"270-800/12V"},
				Channels: "F",
				Reversed: false,
			},
		},

		Dataloggers: []Datalogger{
			Datalogger{
				Dataloggers:   []string{"Q330/3", "Q330/6"},
				Type:          "CW",
				Label:         "LD",
				Rate:          1.0,
				Frequency:     0.1,
				StorageFormat: "Steim2",
				ClockDrift:    0.0001,
				Filters:       []string{"Q330_FLbelow100-1"},
			},
			Datalogger{
				Dataloggers:   []string{"Q330/3", "Q330/6"},
				Type:          "CW",
				Label:         "HD",
				Rate:          100.0,
				Frequency:     15.0,
				StorageFormat: "Steim2",
				ClockDrift:    0.0001,
				Filters:       []string{"Q330_FLbelow100-100"},
			},
			Datalogger{
				Dataloggers:   []string{"Q330S/3", "Q330S/6"},
				Type:          "CW",
				Label:         "LD",
				Rate:          1.0,
				Frequency:     0.1,
				StorageFormat: "Steim2",
				ClockDrift:    0.0001,
				Filters:       []string{"Q330S+_FLbelow100-1"},
			},
			Datalogger{
				Dataloggers:   []string{"Q330S/3", "Q330S/6"},
				Type:          "CW",
				Label:         "HD",
				Rate:          100.0,
				Frequency:     15.0,
				StorageFormat: "Steim2",
				ClockDrift:    0.0001,
				Filters:       []string{"Q330S+_FLbelow100-100"},
			},
			Datalogger{
				Dataloggers:   []string{"Q730/4"},
				Type:          "CW",
				Label:         "LD",
				Rate:          1.0,
				Frequency:     0.1,
				StorageFormat: "Steim2",
				ClockDrift:    0.0001,
				Filters:       []string{"Q4120-1"},
			},
			Datalogger{
				Dataloggers:   []string{"Q730/4"},
				Type:          "CW",
				Label:         "BD",
				Rate:          40.0,
				Frequency:     15.0,
				StorageFormat: "Steim2",
				ClockDrift:    0.0001,
				Filters:       []string{"Q4120-40"},
				Match:         "FWVZ",
			},
			Datalogger{
				Dataloggers:   []string{"Q730/4"},
				Type:          "CW",
				Label:         "HD",
				Rate:          100.0,
				Frequency:     15.0,
				StorageFormat: "Steim2",
				ClockDrift:    0.0001,
				Filters:       []string{"Q4120-100"},
			},
		},
	},

	// Microphones
	Response{
		Sensors: []Sensor{
			Sensor{
				Sensors:  []string{"InfraBSU microphone"},
				Filters:  []string{"InfraBSU microphone"},
				Channels: "F",
				Reversed: false,
			},
		},

		Dataloggers: []Datalogger{
			Datalogger{
				Dataloggers:   []string{"Q330S/3", "Q330S/6"},
				Type:          "CW",
				Label:         "HD",
				Rate:          100.0,
				Frequency:     15,
				StorageFormat: "Steim2",
				ClockDrift:    0.0001,
				Filters:       []string{"Q330S+_FLbelow100-100-PREAMP32"},
			},
			Datalogger{
				Dataloggers:   []string{"Q330S/3", "Q330S/6"},
				Type:          "CW",
				Label:         "LD",
				Rate:          1.0,
				Frequency:     0.1,
				StorageFormat: "Steim2",
				ClockDrift:    0.0001,
				Filters:       []string{"Q330S+_FLbelow100-1-PREAMP32"},
			},
		},
	},
}
