// Code generated by protoc-gen-go.
// source: gloria.proto
// DO NOT EDIT!

/*
Package gloria is a generated protocol buffer package.

It is generated from these files:
	gloria.proto

It has these top-level messages:
	Mark
	Point
	Span
	Receiver
	Firmware
	Antenna
	Radome
	Offset
	InstalledAntenna
	DeployedReceiver
	InstalledRadome
*/
package gloria

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

// A GNSS Mark.
type Mark struct {
	// Code used to uniquely identify the GNSS Mark e.g. TAUP
	// teqc param: -O.mo
	Code string `protobuf:"bytes,1,opt,name=code" json:"code,omitempty"`
	// ITRF DOMES number e.g., 50217M001
	// teqc param: -O.mn
	DomesNumber      string              `protobuf:"bytes,2,opt,name=domes_number,json=domesNumber" json:"domes_number,omitempty"`
	Point            *Point              `protobuf:"bytes,3,opt,name=point" json:"point,omitempty"`
	DeployedReceiver []*DeployedReceiver `protobuf:"bytes,4,rep,name=deployed_receiver,json=deployedReceiver" json:"deployed_receiver,omitempty"`
	InstalledAntenna []*InstalledAntenna `protobuf:"bytes,5,rep,name=installed_antenna,json=installedAntenna" json:"installed_antenna,omitempty"`
	InstalledRadome  []*InstalledRadome  `protobuf:"bytes,6,rep,name=installed_radome,json=installedRadome" json:"installed_radome,omitempty"`
}

func (m *Mark) Reset()                    { *m = Mark{} }
func (m *Mark) String() string            { return proto.CompactTextString(m) }
func (*Mark) ProtoMessage()               {}
func (*Mark) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *Mark) GetCode() string {
	if m != nil {
		return m.Code
	}
	return ""
}

func (m *Mark) GetDomesNumber() string {
	if m != nil {
		return m.DomesNumber
	}
	return ""
}

func (m *Mark) GetPoint() *Point {
	if m != nil {
		return m.Point
	}
	return nil
}

func (m *Mark) GetDeployedReceiver() []*DeployedReceiver {
	if m != nil {
		return m.DeployedReceiver
	}
	return nil
}

func (m *Mark) GetInstalledAntenna() []*InstalledAntenna {
	if m != nil {
		return m.InstalledAntenna
	}
	return nil
}

func (m *Mark) GetInstalledRadome() []*InstalledRadome {
	if m != nil {
		return m.InstalledRadome
	}
	return nil
}

// A geographical point on NZGD2000
type Point struct {
	// Latitude - geographical latitude of the point for the given datum.
	// teqc param: -O.pg[1]
	Latitude float64 `protobuf:"fixed64,1,opt,name=latitude" json:"latitude,omitempty"`
	// Longitude - geographical longitude of the point for the given datum.
	// teqc param: -O.pg[2]
	Longitude float64 `protobuf:"fixed64,2,opt,name=longitude" json:"longitude,omitempty"`
	// Elevation - Height in meters of the point for the given datum.
	// teqc param: -O.pg[3]
	Elevation float64 `protobuf:"fixed64,3,opt,name=elevation" json:"elevation,omitempty"`
}

func (m *Point) Reset()                    { *m = Point{} }
func (m *Point) String() string            { return proto.CompactTextString(m) }
func (*Point) ProtoMessage()               {}
func (*Point) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *Point) GetLatitude() float64 {
	if m != nil {
		return m.Latitude
	}
	return 0
}

func (m *Point) GetLongitude() float64 {
	if m != nil {
		return m.Longitude
	}
	return 0
}

func (m *Point) GetElevation() float64 {
	if m != nil {
		return m.Elevation
	}
	return 0
}

// A time span that has a start and and end.
type Span struct {
	// Start - time in Unix seconds.
	Start int64 `protobuf:"varint,1,opt,name=start" json:"start,omitempty"`
	// End - time in Unix seconds.  A future date of 9999-01-01T00:00:00Z is used to indicate still open.
	End int64 `protobuf:"varint,2,opt,name=end" json:"end,omitempty"`
}

func (m *Span) Reset()                    { *m = Span{} }
func (m *Span) String() string            { return proto.CompactTextString(m) }
func (*Span) ProtoMessage()               {}
func (*Span) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *Span) GetStart() int64 {
	if m != nil {
		return m.Start
	}
	return 0
}

func (m *Span) GetEnd() int64 {
	if m != nil {
		return m.End
	}
	return 0
}

// A GNSS receiver.
type Receiver struct {
	// The receiver model e.g., TRIMBLE NETR9
	// teqc param: -O.rt
	Model string `protobuf:"bytes,1,opt,name=model" json:"model,omitempty"`
	// The receiver serial number e.g., 5033K69574
	// teqc param: -O.rn
	SerialNumber string      `protobuf:"bytes,2,opt,name=serial_number,json=serialNumber" json:"serial_number,omitempty"`
	Firmware     []*Firmware `protobuf:"bytes,3,rep,name=firmware" json:"firmware,omitempty"`
}

func (m *Receiver) Reset()                    { *m = Receiver{} }
func (m *Receiver) String() string            { return proto.CompactTextString(m) }
func (*Receiver) ProtoMessage()               {}
func (*Receiver) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

func (m *Receiver) GetModel() string {
	if m != nil {
		return m.Model
	}
	return ""
}

func (m *Receiver) GetSerialNumber() string {
	if m != nil {
		return m.SerialNumber
	}
	return ""
}

func (m *Receiver) GetFirmware() []*Firmware {
	if m != nil {
		return m.Firmware
	}
	return nil
}

// Firmware versions
type Firmware struct {
	// The firmware version e.g., 5.15
	// teqc param: -O.rv
	Version string `protobuf:"bytes,1,opt,name=version" json:"version,omitempty"`
	Span    *Span  `protobuf:"bytes,2,opt,name=span" json:"span,omitempty"`
}

func (m *Firmware) Reset()                    { *m = Firmware{} }
func (m *Firmware) String() string            { return proto.CompactTextString(m) }
func (*Firmware) ProtoMessage()               {}
func (*Firmware) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{4} }

func (m *Firmware) GetVersion() string {
	if m != nil {
		return m.Version
	}
	return ""
}

func (m *Firmware) GetSpan() *Span {
	if m != nil {
		return m.Span
	}
	return nil
}

// A GNSS antenna
type Antenna struct {
	// The antenna model TRM57971.00
	// teqc param: -O.at[1]
	Model string `protobuf:"bytes,1,opt,name=model" json:"model,omitempty"`
	// The antenna serial number e.g., 1441031450
	// teqc param: -O.an
	SerialNumber string `protobuf:"bytes,2,opt,name=serial_number,json=serialNumber" json:"serial_number,omitempty"`
}

func (m *Antenna) Reset()                    { *m = Antenna{} }
func (m *Antenna) String() string            { return proto.CompactTextString(m) }
func (*Antenna) ProtoMessage()               {}
func (*Antenna) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{5} }

func (m *Antenna) GetModel() string {
	if m != nil {
		return m.Model
	}
	return ""
}

func (m *Antenna) GetSerialNumber() string {
	if m != nil {
		return m.SerialNumber
	}
	return ""
}

// An antenna radome
type Radome struct {
	// The radome model
	// teqc param: -O.at[2]
	Model string `protobuf:"bytes,1,opt,name=model" json:"model,omitempty"`
}

func (m *Radome) Reset()                    { *m = Radome{} }
func (m *Radome) String() string            { return proto.CompactTextString(m) }
func (*Radome) ProtoMessage()               {}
func (*Radome) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{6} }

func (m *Radome) GetModel() string {
	if m != nil {
		return m.Model
	}
	return ""
}

// Offset for an installed antenna
type Offset struct {
	// The vertical offset in m e.g., 0.0550
	// teqc param: -O.pe[1]
	Vertical float64 `protobuf:"fixed64,1,opt,name=vertical" json:"vertical,omitempty"`
	// The offset north in m e.g., 0.0
	// teqc param: -O.pe[2]
	North float64 `protobuf:"fixed64,2,opt,name=north" json:"north,omitempty"`
	// The offset east in m e.g., 0.0
	// teqc param: -O.pe[3]
	East float64 `protobuf:"fixed64,3,opt,name=east" json:"east,omitempty"`
}

func (m *Offset) Reset()                    { *m = Offset{} }
func (m *Offset) String() string            { return proto.CompactTextString(m) }
func (*Offset) ProtoMessage()               {}
func (*Offset) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{7} }

func (m *Offset) GetVertical() float64 {
	if m != nil {
		return m.Vertical
	}
	return 0
}

func (m *Offset) GetNorth() float64 {
	if m != nil {
		return m.North
	}
	return 0
}

func (m *Offset) GetEast() float64 {
	if m != nil {
		return m.East
	}
	return 0
}

type InstalledAntenna struct {
	Antenna *Antenna `protobuf:"bytes,1,opt,name=antenna" json:"antenna,omitempty"`
	Offset  *Offset  `protobuf:"bytes,2,opt,name=offset" json:"offset,omitempty"`
	Span    *Span    `protobuf:"bytes,3,opt,name=span" json:"span,omitempty"`
}

func (m *InstalledAntenna) Reset()                    { *m = InstalledAntenna{} }
func (m *InstalledAntenna) String() string            { return proto.CompactTextString(m) }
func (*InstalledAntenna) ProtoMessage()               {}
func (*InstalledAntenna) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{8} }

func (m *InstalledAntenna) GetAntenna() *Antenna {
	if m != nil {
		return m.Antenna
	}
	return nil
}

func (m *InstalledAntenna) GetOffset() *Offset {
	if m != nil {
		return m.Offset
	}
	return nil
}

func (m *InstalledAntenna) GetSpan() *Span {
	if m != nil {
		return m.Span
	}
	return nil
}

type DeployedReceiver struct {
	Receiver *Receiver `protobuf:"bytes,1,opt,name=receiver" json:"receiver,omitempty"`
	Span     *Span     `protobuf:"bytes,2,opt,name=span" json:"span,omitempty"`
}

func (m *DeployedReceiver) Reset()                    { *m = DeployedReceiver{} }
func (m *DeployedReceiver) String() string            { return proto.CompactTextString(m) }
func (*DeployedReceiver) ProtoMessage()               {}
func (*DeployedReceiver) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{9} }

func (m *DeployedReceiver) GetReceiver() *Receiver {
	if m != nil {
		return m.Receiver
	}
	return nil
}

func (m *DeployedReceiver) GetSpan() *Span {
	if m != nil {
		return m.Span
	}
	return nil
}

type InstalledRadome struct {
	Radome *Radome `protobuf:"bytes,1,opt,name=radome" json:"radome,omitempty"`
	Span   *Span   `protobuf:"bytes,2,opt,name=span" json:"span,omitempty"`
}

func (m *InstalledRadome) Reset()                    { *m = InstalledRadome{} }
func (m *InstalledRadome) String() string            { return proto.CompactTextString(m) }
func (*InstalledRadome) ProtoMessage()               {}
func (*InstalledRadome) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{10} }

func (m *InstalledRadome) GetRadome() *Radome {
	if m != nil {
		return m.Radome
	}
	return nil
}

func (m *InstalledRadome) GetSpan() *Span {
	if m != nil {
		return m.Span
	}
	return nil
}

func init() {
	proto.RegisterType((*Mark)(nil), "gloria.Mark")
	proto.RegisterType((*Point)(nil), "gloria.Point")
	proto.RegisterType((*Span)(nil), "gloria.Span")
	proto.RegisterType((*Receiver)(nil), "gloria.Receiver")
	proto.RegisterType((*Firmware)(nil), "gloria.Firmware")
	proto.RegisterType((*Antenna)(nil), "gloria.Antenna")
	proto.RegisterType((*Radome)(nil), "gloria.Radome")
	proto.RegisterType((*Offset)(nil), "gloria.Offset")
	proto.RegisterType((*InstalledAntenna)(nil), "gloria.InstalledAntenna")
	proto.RegisterType((*DeployedReceiver)(nil), "gloria.DeployedReceiver")
	proto.RegisterType((*InstalledRadome)(nil), "gloria.InstalledRadome")
}

func init() { proto.RegisterFile("gloria.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 521 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0x9c, 0x54, 0xdd, 0x8e, 0xd3, 0x3c,
	0x10, 0x55, 0x9a, 0x36, 0xed, 0x4e, 0xbb, 0x5f, 0xf3, 0x59, 0x2b, 0x11, 0x21, 0x84, 0x4a, 0x56,
	0x42, 0x45, 0x42, 0xbd, 0x28, 0x4f, 0xc0, 0x6a, 0x59, 0x89, 0x0b, 0x16, 0x64, 0xee, 0xe0, 0x22,
	0x72, 0x9b, 0xe9, 0x62, 0xe1, 0xda, 0x91, 0xe3, 0x2d, 0xe2, 0x09, 0x78, 0x21, 0x1e, 0x10, 0xf9,
	0x2f, 0x55, 0x03, 0x08, 0xc4, 0x9d, 0xe7, 0x9c, 0xc9, 0xf1, 0xcc, 0x1c, 0x4f, 0x60, 0x76, 0x27,
	0x94, 0xe6, 0x6c, 0xd5, 0x68, 0x65, 0x14, 0xc9, 0x7c, 0x54, 0x7e, 0x1f, 0xc0, 0xf0, 0x0d, 0xd3,
	0x9f, 0x09, 0x81, 0xe1, 0x56, 0xd5, 0x58, 0x24, 0x8b, 0x64, 0x79, 0x46, 0xdd, 0x99, 0x3c, 0x81,
	0x59, 0xad, 0xf6, 0xd8, 0x56, 0xf2, 0x7e, 0xbf, 0x41, 0x5d, 0x0c, 0x1c, 0x37, 0x75, 0xd8, 0xad,
	0x83, 0xc8, 0x25, 0x8c, 0x1a, 0xc5, 0xa5, 0x29, 0xd2, 0x45, 0xb2, 0x9c, 0xae, 0xcf, 0x57, 0xe1,
	0x96, 0x77, 0x16, 0xa4, 0x9e, 0x23, 0xaf, 0xe0, 0xff, 0x1a, 0x1b, 0xa1, 0xbe, 0x62, 0x5d, 0x69,
	0xdc, 0x22, 0x3f, 0xa0, 0x2e, 0x86, 0x8b, 0x74, 0x39, 0x5d, 0x17, 0xf1, 0x83, 0xeb, 0x90, 0x40,
	0x03, 0x4f, 0xf3, 0xba, 0x87, 0x58, 0x19, 0x2e, 0x5b, 0xc3, 0x84, 0xc0, 0xba, 0x62, 0xd2, 0xa0,
	0x94, 0xac, 0x18, 0x9d, 0xca, 0xbc, 0x8e, 0x09, 0x2f, 0x3d, 0x4f, 0x73, 0xde, 0x43, 0xc8, 0x15,
	0x1c, 0xb1, 0x4a, 0x33, 0xdb, 0x4d, 0x91, 0x39, 0x95, 0x07, 0x3f, 0xa9, 0x50, 0x47, 0xd3, 0x39,
	0x3f, 0x05, 0xca, 0x0a, 0x46, 0xae, 0x43, 0xf2, 0x10, 0x26, 0x82, 0x19, 0x6e, 0xee, 0xc3, 0xe8,
	0x12, 0xda, 0xc5, 0xe4, 0x11, 0x9c, 0x09, 0x25, 0xef, 0x3c, 0x39, 0x70, 0xe4, 0x11, 0xb0, 0x2c,
	0x0a, 0x3c, 0x30, 0xc3, 0x95, 0x74, 0xd3, 0x4b, 0xe8, 0x11, 0x28, 0x57, 0x30, 0x7c, 0xdf, 0x30,
	0x49, 0x2e, 0x60, 0xd4, 0x1a, 0xa6, 0x8d, 0x13, 0x4f, 0xa9, 0x0f, 0x48, 0x0e, 0x29, 0xca, 0xda,
	0x69, 0xa6, 0xd4, 0x1e, 0xcb, 0x16, 0x26, 0xdd, 0x9c, 0x2e, 0x60, 0xb4, 0x57, 0x35, 0x8a, 0xe0,
	0xa5, 0x0f, 0xc8, 0x25, 0x9c, 0xb7, 0xa8, 0x39, 0x13, 0xa7, 0x6e, 0xce, 0x3c, 0x18, 0xec, 0x7c,
	0x0e, 0x93, 0x1d, 0xd7, 0xfb, 0x2f, 0x4c, 0x63, 0x91, 0xba, 0x99, 0xe4, 0x71, 0x26, 0x37, 0x01,
	0xa7, 0x5d, 0x46, 0x79, 0x03, 0x93, 0x88, 0x92, 0x02, 0xc6, 0x07, 0xd4, 0xad, 0x6d, 0xc6, 0x5f,
	0x1b, 0x43, 0xb2, 0x80, 0x61, 0xdb, 0x30, 0xe9, 0xee, 0x9b, 0xae, 0x67, 0x51, 0xcf, 0xb6, 0x47,
	0x1d, 0x53, 0x5e, 0xc3, 0x38, 0x9a, 0xf3, 0xef, 0xb5, 0x97, 0x8f, 0x21, 0xf3, 0xee, 0xfc, 0x5a,
	0xa4, 0xbc, 0x85, 0xec, 0xed, 0x6e, 0xd7, 0xa2, 0x33, 0xed, 0x80, 0xda, 0xf0, 0x2d, 0x13, 0xd1,
	0xb4, 0x18, 0xdb, 0x6f, 0xa5, 0xd2, 0xe6, 0x53, 0x30, 0xcc, 0x07, 0x76, 0x3b, 0x90, 0xb5, 0x26,
	0xf8, 0xe4, 0xce, 0xe5, 0xb7, 0x04, 0xf2, 0xfe, 0x73, 0x23, 0xcf, 0x60, 0x1c, 0x5f, 0x66, 0xe2,
	0xfa, 0x9d, 0xc7, 0x7e, 0xe3, 0x83, 0x8c, 0x3c, 0x79, 0x0a, 0x99, 0x72, 0xf5, 0x84, 0xc9, 0xfc,
	0x17, 0x33, 0x7d, 0x95, 0x34, 0xb0, 0xdd, 0xfc, 0xd2, 0xdf, 0xce, 0x6f, 0x03, 0x79, 0x7f, 0x7d,
	0xac, 0x93, 0xdd, 0xaa, 0xf9, 0x4a, 0x3a, 0x27, 0xbb, 0x15, 0xeb, 0x32, 0xfe, 0xc2, 0xa3, 0x8f,
	0x30, 0xef, 0x6d, 0x85, 0x6d, 0x20, 0xac, 0x4f, 0x72, 0xda, 0x40, 0xd8, 0x9a, 0xc0, 0xfe, 0x59,
	0xfc, 0x6a, 0xf2, 0x21, 0xfc, 0x8f, 0x36, 0x99, 0xfb, 0x3d, 0xbd, 0xf8, 0x11, 0x00, 0x00, 0xff,
	0xff, 0xfe, 0xcb, 0x46, 0xe7, 0xae, 0x04, 0x00, 0x00,
}
