package main

var slates = map[string][]Altus{
	"BKZ": {
		{
			Installed: "2013/10/09,00:00:01",
			DevCode:   "Q33",
			InstId:    "294",
			Removed:   "2016/04/19,02:15:00",
			Pins: []Pin{
				{
					PinNo:    0,
					Azimuth:  "0.0",
					Dip:      "-90.0",
					InstCode: "z",
					Reversed: "no",
					SeisCode: "EPI",
					StreamId: "BKZ/20-HNZ/NZ",
				},
				{
					PinNo:    1,
					Azimuth:  "0.0",
					Dip:      "0.0",
					InstCode: "n",
					Reversed: "no",
					SeisCode: "EPI",
					StreamId: "BKZ/20-HNN/NZ",
				},
				{
					PinNo:    2,
					Azimuth:  "90.0",
					Dip:      "0.0",
					InstCode: "e",
					Reversed: "no",
					SeisCode: "EPI",
					StreamId: "BKZ/20-HNE/NZ",
				},
			},
		},
		{
			Installed: "2016/01/29,13:25:01",
			DevCode:   "Q33",
			InstId:    "285",
			Removed:   "9999/01/01,00:00:00",
			Pins: []Pin{
				{
					PinNo:    0,
					Azimuth:  "0.0",
					Dip:      "-90.0",
					InstCode: "z",
					Reversed: "no",
					SeisCode: "EPI",
					StreamId: "BKZ/20-HNZ/NZ",
				},
				{
					PinNo:    1,
					Azimuth:  "0.0",
					Dip:      "0.0",
					InstCode: "n",
					Reversed: "no",
					SeisCode: "EPI",
					StreamId: "BKZ/20-HNN/NZ",
				},
				{
					PinNo:    2,
					Azimuth:  "90.0",
					Dip:      "0.0",
					InstCode: "e",
					Reversed: "no",
					SeisCode: "EPI",
					StreamId: "BKZ/20-HNE/NZ",
				},
			},
		},
	},
	"CTZ": {
		{
			Installed: "2007/12/15,07:00:03",
			DevCode:   "Q33",
			InstId:    "294",
			Removed:   "2008/11/25,01:30:00",
			Pins: []Pin{
				{
					PinNo:    0,
					Azimuth:  "0.0",
					Dip:      "-90.0",
					InstCode: "z",
					Reversed: "no",
					SeisCode: "EPI",
					StreamId: "CTZ/20-HNZ/NZ",
				},
				{
					PinNo:    1,
					Azimuth:  "0.0",
					Dip:      "0.0",
					InstCode: "n",
					Reversed: "no",
					SeisCode: "EPI",
					StreamId: "CTZ/20-HNN/NZ",
				},
				{
					PinNo:    2,
					Azimuth:  "90.0",
					Dip:      "0.0",
					InstCode: "e",
					Reversed: "no",
					SeisCode: "EPI",
					StreamId: "CTZ/20-HNE/NZ",
				},
			},
		},
		{
			Installed: "2008/11/25,02:01:00",
			DevCode:   "Q33",
			InstId:    "294",
			Removed:   "2008/11/26,00:00:00",
			Pins: []Pin{
				{
					PinNo:    0,
					Azimuth:  "0.0",
					Dip:      "-90.0",
					InstCode: "z",
					Reversed: "no",
					SeisCode: "EPI",
					StreamId: "CTZ/20-HNZ/NZ",
				},
				{
					PinNo:    1,
					Azimuth:  "0.0",
					Dip:      "0.0",
					InstCode: "n",
					Reversed: "no",
					SeisCode: "EPI",
					StreamId: "CTZ/20-HNN/NZ",
				},
				{
					PinNo:    2,
					Azimuth:  "90.0",
					Dip:      "0.0",
					InstCode: "e",
					Reversed: "no",
					SeisCode: "EPI",
					StreamId: "CTZ/20-HNE/NZ",
				},
			},
		},
		{
			Installed: "2008/11/26,00:00:01",
			DevCode:   "Q33",
			InstId:    "299",
			Removed:   "2013/01/14,00:00:00",
			Pins: []Pin{
				{
					PinNo:    0,
					Azimuth:  "0.0",
					Dip:      "-90.0",
					InstCode: "z",
					Reversed: "no",
					SeisCode: "EPI",
					StreamId: "CTZ/20-HNZ/NZ",
				},
				{
					PinNo:    1,
					Azimuth:  "0.0",
					Dip:      "0.0",
					InstCode: "n",
					Reversed: "no",
					SeisCode: "EPI",
					StreamId: "CTZ/20-HNN/NZ",
				},
				{
					PinNo:    2,
					Azimuth:  "90.0",
					Dip:      "0.0",
					InstCode: "e",
					Reversed: "no",
					SeisCode: "EPI",
					StreamId: "CTZ/20-HNE/NZ",
				},
			},
		},
	},
	"DCZ": {
		{
			Installed: "2012/07/19,00:00:01",
			DevCode:   "Q33",
			InstId:    "330",
			Removed:   "2015/10/22,00:00:00",
			Pins: []Pin{
				{
					PinNo:    0,
					Azimuth:  "0.0",
					Dip:      "-90.0",
					InstCode: "z",
					Reversed: "no",
					SeisCode: "EPI",
					StreamId: "DCZ/20-HNZ/NZ",
				},
				{
					PinNo:    1,
					Azimuth:  "0.0",
					Dip:      "0.0",
					InstCode: "n",
					Reversed: "no",
					SeisCode: "EPI",
					StreamId: "DCZ/20-HNN/NZ",
				},
				{
					PinNo:    2,
					Azimuth:  "90.0",
					Dip:      "0.0",
					InstCode: "e",
					Reversed: "no",
					SeisCode: "EPI",
					StreamId: "DCZ/20-HNE/NZ",
				},
			},
		},
	},

	"DSZ": {
		{
			Installed: "2013/07/22,08:00:01",
			DevCode:   "Q33",
			InstId:    "382",
			Removed:   "2016/02/26,11:10:00",
			Pins: []Pin{
				{
					PinNo:    0,
					Azimuth:  "0.0",
					Dip:      "-90.0",
					InstCode: "z",
					Reversed: "no",
					SeisCode: "EPI",
					StreamId: "DSZ/20-HNZ/NZ",
				},
				{
					PinNo:    1,
					Azimuth:  "0.0",
					Dip:      "0.0",
					InstCode: "n",
					Reversed: "no",
					SeisCode: "EPI",
					StreamId: "DSZ/20-HNN/NZ",
				},
				{
					PinNo:    2,
					Azimuth:  "90.0",
					Dip:      "0.0",
					InstCode: "e",
					Reversed: "no",
					SeisCode: "EPI",
					StreamId: "DSZ/20-HNE/NZ",
				},
			},
		},
		{
			Installed: "2015/12/11,13:00:01",
			DevCode:   "Q33",
			InstId:    "332",
			Removed:   "2016/11/09,08:00:00",
			Pins: []Pin{
				{
					PinNo:    0,
					Azimuth:  "0.0",
					Dip:      "-90.0",
					InstCode: "z",
					Reversed: "no",
					SeisCode: "EPI",
					StreamId: "DSZ/20-HNZ/NZ",
				},
				{
					PinNo:    1,
					Azimuth:  "0.0",
					Dip:      "0.0",
					InstCode: "n",
					Reversed: "no",
					SeisCode: "EPI",
					StreamId: "DSZ/20-HNN/NZ",
				},
				{
					PinNo:    2,
					Azimuth:  "90.0",
					Dip:      "0.0",
					InstCode: "e",
					Reversed: "no",
					SeisCode: "EPI",
					StreamId: "DSZ/20-HNE/NZ",
				},
			},
		},
	},

	"HAZ": {
		{
			Installed: "2010/01/14,10:05:00",
			DevCode:   "Q33",
			InstId:    "286",
			Removed:   "2013/01/11,00:00:00",

			Pins: []Pin{
				{
					PinNo:    0,
					Azimuth:  "0.0",
					Dip:      "-90.0",
					InstCode: "z",
					Reversed: "no",
					SeisCode: "EPI",
					StreamId: "HAZ/20-HNZ/NZ",
				},
				{
					PinNo:    1,
					Azimuth:  "0.0",
					Dip:      "0.0",
					InstCode: "n",
					Reversed: "no",
					SeisCode: "EPI",
					StreamId: "HAZ/20-HNN/NZ",
				},
				{
					PinNo:    2,
					Azimuth:  "90.0",
					Dip:      "0.0",
					InstCode: "e",
					Reversed: "no",
					SeisCode: "EPI",
					StreamId: "HAZ/20-HNE/NZ",
				},
			},
		},
		{
			Installed: "2013/01/11,00:00:01",
			DevCode:   "Q33",
			InstId:    "391",
			Removed:   "2016/01/14,09:20:00",

			Pins: []Pin{
				{
					PinNo:    0,
					Azimuth:  "0.0",
					Dip:      "-90.0",
					InstCode: "z",
					Reversed: "no",
					SeisCode: "EPI",
					StreamId: "HAZ/20-HNZ/NZ",
				},
				{
					PinNo:    1,
					Azimuth:  "0.0",
					Dip:      "0.0",
					InstCode: "n",
					Reversed: "no",
					SeisCode: "EPI",
					StreamId: "HAZ/20-HNN/NZ",
				},
				{
					PinNo:    2,
					Azimuth:  "90.0",
					Dip:      "0.0",
					InstCode: "e",
					Reversed: "no",
					SeisCode: "EPI",
					StreamId: "HAZ/20-HNE/NZ",
				},
			},
		},
	},

	"HIZ": {
		{
			Installed: "2016/01/25,00:00:01",
			DevCode:   "Q33",
			InstId:    "330",
			Removed:   "9999/01/01,00:00:00",

			Pins: []Pin{
				{
					PinNo:    0,
					Azimuth:  "0.0",
					Dip:      "-90.0",
					InstCode: "z",
					Reversed: "no",
					SeisCode: "EPI",
					StreamId: "HIZ/20-HNZ/NZ",
				},
				{
					PinNo:    1,
					Azimuth:  "0.0",
					Dip:      "0.0",
					InstCode: "n",
					Reversed: "no",
					SeisCode: "EPI",
					StreamId: "HIZ/20-HNN/NZ",
				},
				{
					PinNo:    2,
					Azimuth:  "90.0",
					Dip:      "0.0",
					InstCode: "e",
					Reversed: "no",
					SeisCode: "EPI",
					StreamId: "HIZ/20-HNE/NZ",
				},
			},
		},
	},

	"KNZ": {
		{
			Installed: "2009/04/27,03:30:01",
			DevCode:   "Q33",
			InstId:    "146",
			Removed:   "2015/12/07,21:00:00",

			Pins: []Pin{
				{
					PinNo:    0,
					Azimuth:  "0.0",
					Dip:      "-90.0",
					InstCode: "z",
					Reversed: "no",
					SeisCode: "EPI",
					StreamId: "KNZ/20-HNZ/NZ",
				},
				{
					PinNo:    1,
					Azimuth:  "0.0",
					Dip:      "0.0",
					InstCode: "n",
					Reversed: "no",
					SeisCode: "EPI",
					StreamId: "KNZ/20-HNN/NZ",
				},
				{
					PinNo:    2,
					Azimuth:  "90.0",
					Dip:      "0.0",
					InstCode: "e",
					Reversed: "no",
					SeisCode: "EPI",
					StreamId: "KNZ/20-HNE/NZ",
				},
			},
		},
		{
			Installed: "2015/12/07,21:00:01",
			DevCode:   "Q33",
			InstId:    "303",
			Removed:   "9999/01/01,00:00:00",

			Pins: []Pin{
				{
					PinNo:    0,
					Azimuth:  "0.0",
					Dip:      "-90.0",
					InstCode: "z",
					Reversed: "no",
					SeisCode: "EPI",
					StreamId: "KNZ/20-HNZ/NZ",
				},
				{
					PinNo:    1,
					Azimuth:  "0.0",
					Dip:      "0.0",
					InstCode: "n",
					Reversed: "no",
					SeisCode: "EPI",
					StreamId: "KNZ/20-HNN/NZ",
				},
				{
					PinNo:    2,
					Azimuth:  "90.0",
					Dip:      "0.0",
					InstCode: "e",
					Reversed: "no",
					SeisCode: "EPI",
					StreamId: "KNZ/20-HNE/NZ",
				},
			},
		},
	},

	"KHZ": {
		{
			Installed: "2011/02/23,04:00:01",
			DevCode:   "Q33",
			InstId:    "285",
			Removed:   "2016/01/29,13:25:00",

			Pins: []Pin{
				{
					PinNo:    0,
					Azimuth:  "0.0",
					Dip:      "-90.0",
					InstCode: "z",
					Reversed: "no",
					SeisCode: "EPI",
					StreamId: "KHZ/20-HNZ/NZ",
				},
				{
					PinNo:    1,
					Azimuth:  "0.0",
					Dip:      "0.0",
					InstCode: "n",
					Reversed: "no",
					SeisCode: "EPI",
					StreamId: "KHZ/20-HNN/NZ",
				},
				{
					PinNo:    2,
					Azimuth:  "90.0",
					Dip:      "0.0",
					InstCode: "e",
					Reversed: "no",
					SeisCode: "EPI",
					StreamId: "KHZ/20-HNE/NZ",
				},
			},
		},
		{
			Installed: "2016/02/26,11:10:01",
			DevCode:   "Q33",
			InstId:    "287",
			Removed:   "9999/01/01,00:00:00",

			Pins: []Pin{
				{
					PinNo:    0,
					Azimuth:  "0.0",
					Dip:      "-90.0",
					InstCode: "z",
					Reversed: "no",
					SeisCode: "EPI",
					StreamId: "KHZ/20-HNZ/NZ",
				},
				{
					PinNo:    1,
					Azimuth:  "0.0",
					Dip:      "0.0",
					InstCode: "n",
					Reversed: "no",
					SeisCode: "EPI",
					StreamId: "KHZ/20-HNN/NZ",
				},
				{
					PinNo:    2,
					Azimuth:  "90.0",
					Dip:      "0.0",
					InstCode: "e",
					Reversed: "no",
					SeisCode: "EPI",
					StreamId: "KHZ/20-HNE/NZ",
				},
			},
		},
	},

	"KUZ": {
		{
			Installed: "2016/02/26,11:10:01",
			DevCode:   "Q33",
			InstId:    "382",
			Removed:   "9999/01/01,00:00:00",

			Pins: []Pin{
				{
					PinNo:    0,
					Azimuth:  "0.0",
					Dip:      "-90.0",
					InstCode: "z",
					Reversed: "no",
					SeisCode: "EPI",
					StreamId: "KUZ/20-HNZ/NZ",
				},
				{
					PinNo:    1,
					Azimuth:  "0.0",
					Dip:      "0.0",
					InstCode: "n",
					Reversed: "no",
					SeisCode: "EPI",
					StreamId: "KUZ/20-HNN/NZ",
				},
				{
					PinNo:    2,
					Azimuth:  "90.0",
					Dip:      "0.0",
					InstCode: "e",
					Reversed: "no",
					SeisCode: "EPI",
					StreamId: "KUZ/20-HNE/NZ",
				},
			},
		},
	},

	"MSZ": {
		{
			Installed: "2013/03/26,00:00:01",
			DevCode:   "Q33",
			InstId:    "367",
			Removed:   "2016/04/19,23:00:00",

			Pins: []Pin{
				{
					PinNo:    0,
					Azimuth:  "0.0",
					Dip:      "-90.0",
					InstCode: "z",
					Reversed: "no",
					SeisCode: "EPI",
					StreamId: "MSZ/20-HNZ/NZ",
				},
				{
					PinNo:    1,
					Azimuth:  "0.0",
					Dip:      "0.0",
					InstCode: "n",
					Reversed: "no",
					SeisCode: "EPI",
					StreamId: "MSZ/20-HNN/NZ",
				},
				{
					PinNo:    2,
					Azimuth:  "90.0",
					Dip:      "0.0",
					InstCode: "e",
					Reversed: "no",
					SeisCode: "EPI",
					StreamId: "MSZ/20-HNE/NZ",
				},
			},
		},
		{
			Installed: "2016/04/19,23:00:01",
			DevCode:   "Q33",
			InstId:    "299",
			Removed:   "9999/01/01,00:00:00",

			Pins: []Pin{
				{
					PinNo:    0,
					Azimuth:  "0.0",
					Dip:      "-90.0",
					InstCode: "z",
					Reversed: "no",
					SeisCode: "EPI",
					StreamId: "MSZ/20-HNZ/NZ",
				},
				{
					PinNo:    1,
					Azimuth:  "0.0",
					Dip:      "0.0",
					InstCode: "n",
					Reversed: "no",
					SeisCode: "EPI",
					StreamId: "MSZ/20-HNN/NZ",
				},
				{
					PinNo:    2,
					Azimuth:  "90.0",
					Dip:      "0.0",
					InstCode: "e",
					Reversed: "no",
					SeisCode: "EPI",
					StreamId: "MSZ/20-HNE/NZ",
				},
			},
		},
	},

	"ODZ": {
		{
			Installed: "2008/07/22,02:20:01",
			DevCode:   "Q33",
			InstId:    "287",
			Removed:   "2015/10/21,14:25:00",

			Pins: []Pin{
				{
					PinNo:    0,
					Azimuth:  "0.0",
					Dip:      "-90.0",
					InstCode: "z",
					Reversed: "no",
					SeisCode: "EPI",
					StreamId: "ODZ/20-HNZ/NZ",
				},
				{
					PinNo:    1,
					Azimuth:  "0.0",
					Dip:      "0.0",
					InstCode: "n",
					Reversed: "no",
					SeisCode: "EPI",
					StreamId: "ODZ/20-HNN/NZ",
				},
				{
					PinNo:    2,
					Azimuth:  "90.0",
					Dip:      "0.0",
					InstCode: "e",
					Reversed: "no",
					SeisCode: "EPI",
					StreamId: "ODZ/20-HNE/NZ",
				},
			},
		},
		{
			Installed: "2015/10/21,14:25:01",
			DevCode:   "Q33",
			InstId:    "292",
			Removed:   "9999/01/01,00:00:00",

			Pins: []Pin{
				{
					PinNo:    0,
					Azimuth:  "0.0",
					Dip:      "-90.0",
					InstCode: "z",
					Reversed: "no",
					SeisCode: "EPI",
					StreamId: "ODZ/20-HNZ/NZ",
				},
				{
					PinNo:    1,
					Azimuth:  "0.0",
					Dip:      "0.0",
					InstCode: "n",
					Reversed: "no",
					SeisCode: "EPI",
					StreamId: "ODZ/20-HNN/NZ",
				},
				{
					PinNo:    2,
					Azimuth:  "90.0",
					Dip:      "0.0",
					InstCode: "e",
					Reversed: "no",
					SeisCode: "EPI",
					StreamId: "ODZ/20-HNE/NZ",
				},
			},
		},
	},

	"PYZ": {
		{
			Installed: "2009/07/25,00:30:01",
			DevCode:   "Q33",
			InstId:    "302",
			Removed:   "2009/09/15,01:35:00",

			Pins: []Pin{
				{
					PinNo:    0,
					Azimuth:  "0.0",
					Dip:      "-90.0",
					InstCode: "z",
					Reversed: "no",
					SeisCode: "EPI",
					StreamId: "PYZ/20-HNZ/NZ",
				},
				{
					PinNo:    1,
					Azimuth:  "0.0",
					Dip:      "0.0",
					InstCode: "n",
					Reversed: "no",
					SeisCode: "EPI",
					StreamId: "PYZ/20-HNN/NZ",
				},
				{
					PinNo:    2,
					Azimuth:  "90.0",
					Dip:      "0.0",
					InstCode: "e",
					Reversed: "no",
					SeisCode: "EPI",
					StreamId: "PYZ/20-HNE/NZ",
				},
			},
		},
		{
			Installed: "2009/09/15,01:50:01",
			DevCode:   "Q33",
			InstId:    "303",
			Removed:   "2014/11/25,00:00:10",

			Pins: []Pin{
				{
					PinNo:    0,
					Azimuth:  "0.0",
					Dip:      "-90.0",
					InstCode: "z",
					Reversed: "no",
					SeisCode: "EPI",
					StreamId: "PYZ/20-HNZ/NZ",
				},
				{
					PinNo:    1,
					Azimuth:  "0.0",
					Dip:      "0.0",
					InstCode: "n",
					Reversed: "no",
					SeisCode: "EPI",
					StreamId: "PYZ/20-HNN/NZ",
				},
				{
					PinNo:    2,
					Azimuth:  "90.0",
					Dip:      "0.0",
					InstCode: "e",
					Reversed: "no",
					SeisCode: "EPI",
					StreamId: "PYZ/20-HNE/NZ",
				},
			},
		},
		{
			Installed: "2014/11/25,00:00:11",
			DevCode:   "Q33",
			InstId:    "286",
			Removed:   "2016/04/19,02:15:00",

			Pins: []Pin{
				{
					PinNo:    0,
					Azimuth:  "0.0",
					Dip:      "-90.0",
					InstCode: "z",
					Reversed: "no",
					SeisCode: "EPI",
					StreamId: "PYZ/20-HNZ/NZ",
				},
				{
					PinNo:    1,
					Azimuth:  "0.0",
					Dip:      "0.0",
					InstCode: "n",
					Reversed: "no",
					SeisCode: "EPI",
					StreamId: "PYZ/20-HNN/NZ",
				},
				{
					PinNo:    2,
					Azimuth:  "90.0",
					Dip:      "0.0",
					InstCode: "e",
					Reversed: "no",
					SeisCode: "EPI",
					StreamId: "PYZ/20-HNE/NZ",
				},
			},
		},
		{
			Installed: "2016/04/19,02:15:01",
			DevCode:   "Q33",
			InstId:    "294",
			Removed:   "2017/01/19,21:30:00",

			Pins: []Pin{
				{
					PinNo:    0,
					Azimuth:  "0.0",
					Dip:      "-90.0",
					InstCode: "z",
					Reversed: "no",
					SeisCode: "EPI",
					StreamId: "PYZ/20-HNZ/NZ",
				},
				{
					PinNo:    1,
					Azimuth:  "0.0",
					Dip:      "0.0",
					InstCode: "n",
					Reversed: "no",
					SeisCode: "EPI",
					StreamId: "PYZ/20-HNN/NZ",
				},
				{
					PinNo:    2,
					Azimuth:  "90.0",
					Dip:      "0.0",
					InstCode: "e",
					Reversed: "no",
					SeisCode: "EPI",
					StreamId: "PYZ/20-HNE/NZ",
				},
			},
		},
	},
	"RIZ": {
		{
			Installed: "2009/05/18,01:00:00",
			DevCode:   "Q33",
			InstId:    "300",
			Removed:   "2015/12/18,00:00:00",

			Pins: []Pin{
				{
					PinNo:    0,
					Azimuth:  "0.0",
					Dip:      "-90.0",
					InstCode: "z",
					Reversed: "no",
					SeisCode: "EPI",
					StreamId: "RIZ/20-HNZ/NZ",
				},
				{
					PinNo:    1,
					Azimuth:  "0.0",
					Dip:      "0.0",
					InstCode: "n",
					Reversed: "no",
					SeisCode: "EPI",
					StreamId: "RIZ/20-HNN/NZ",
				},
				{
					PinNo:    2,
					Azimuth:  "90.0",
					Dip:      "0.0",
					InstCode: "e",
					Reversed: "no",
					SeisCode: "EPI",
					StreamId: "RIZ/20-HNE/NZ",
				},
			},
		},
		{
			Installed: "2015/12/18,00:00:01",
			DevCode:   "Q33",
			InstId:    "302",
			Removed:   "2016/09/17,13:00:00",

			Pins: []Pin{
				{
					PinNo:    0,
					Azimuth:  "0.0",
					Dip:      "-90.0",
					InstCode: "z",
					Reversed: "no",
					SeisCode: "EPI",
					StreamId: "RIZ/20-HNZ/NZ",
				},
				{
					PinNo:    1,
					Azimuth:  "0.0",
					Dip:      "0.0",
					InstCode: "n",
					Reversed: "no",
					SeisCode: "EPI",
					StreamId: "RIZ/20-HNN/NZ",
				},
				{
					PinNo:    2,
					Azimuth:  "90.0",
					Dip:      "0.0",
					InstCode: "e",
					Reversed: "no",
					SeisCode: "EPI",
					StreamId: "RIZ/20-HNE/NZ",
				},
			},
		},
	},

	"SYZ": {
		{
			Installed: "2012/08/02,00:00:01",
			DevCode:   "Q33",
			InstId:    "332",
			Removed:   "2015/10/27,01:00:00",

			Pins: []Pin{
				{
					PinNo:    0,
					Azimuth:  "0.0",
					Dip:      "-90.0",
					InstCode: "z",
					Reversed: "no",
					SeisCode: "EPI",
					StreamId: "SYZ/20-HNZ/NZ",
				},
				{
					PinNo:    1,
					Azimuth:  "0.0",
					Dip:      "0.0",
					InstCode: "n",
					Reversed: "no",
					SeisCode: "EPI",
					StreamId: "SYZ/20-HNN/NZ",
				},
				{
					PinNo:    2,
					Azimuth:  "90.0",
					Dip:      "0.0",
					InstCode: "e",
					Reversed: "no",
					SeisCode: "EPI",
					StreamId: "SYZ/20-HNE/NZ",
				},
			},
		},
		{
			Installed: "2015/10/27,01:00:01",
			DevCode:   "Q33",
			InstId:    "304",
			Removed:   "9999/01/01,00:00:00",

			Pins: []Pin{
				{
					PinNo:    0,
					Azimuth:  "0.0",
					Dip:      "-90.0",
					InstCode: "z",
					Reversed: "no",
					SeisCode: "EPI",
					StreamId: "SYZ/20-HNZ/NZ",
				},
				{
					PinNo:    1,
					Azimuth:  "0.0",
					Dip:      "0.0",
					InstCode: "n",
					Reversed: "no",
					SeisCode: "EPI",
					StreamId: "SYZ/20-HNN/NZ",
				},
				{
					PinNo:    2,
					Azimuth:  "90.0",
					Dip:      "0.0",
					InstCode: "e",
					Reversed: "no",
					SeisCode: "EPI",
					StreamId: "SYZ/20-HNE/NZ",
				},
			},
		},
	},

	"OUZ": {
		{
			Installed: "2010/02/24,00:00:01",
			DevCode:   "Q33",
			InstId:    "284",
			Removed:   "2016/03/14,01:15:00",

			Pins: []Pin{
				{
					PinNo:    0,
					Azimuth:  "0.0",
					Dip:      "-90.0",
					InstCode: "z",
					Reversed: "no",
					SeisCode: "EPI",
					StreamId: "OUZ/20-HNZ/NZ",
				},
				{
					PinNo:    1,
					Azimuth:  "0.0",
					Dip:      "0.0",
					InstCode: "n",
					Reversed: "no",
					SeisCode: "EPI",
					StreamId: "OUZ/20-HNN/NZ",
				},
				{
					PinNo:    2,
					Azimuth:  "90.0",
					Dip:      "0.0",
					InstCode: "e",
					Reversed: "no",
					SeisCode: "EPI",
					StreamId: "OUZ/20-HNE/NZ",
				},
			},
		},
	},
	"WCZ": {
		{
			Installed: "2016/02/16,00:00:01",
			DevCode:   "Q33",
			InstId:    "297",
			Removed:   "2017/02/22,03:00:00",
			Pins: []Pin{
				{
					PinNo:    0,
					Azimuth:  "0.0",
					Dip:      "-90.0",
					InstCode: "z",
					Reversed: "no",
					SeisCode: "EPI",
					StreamId: "WCZ/20-HNZ/NZ",
				},
				{
					PinNo:    1,
					Azimuth:  "0.0",
					Dip:      "0.0",
					InstCode: "n",
					Reversed: "no",
					SeisCode: "EPI",
					StreamId: "WCZ/20-HNN/NZ",
				},
				{
					PinNo:    2,
					Azimuth:  "90.0",
					Dip:      "0.0",
					InstCode: "e",
					Reversed: "no",
					SeisCode: "EPI",
					StreamId: "WCZ/20-HNE/NZ",
				},
			},
		},
	},
	"WEL": {
		{
			Installed: "2013/08/13,22:00:01",
			DevCode:   "Q33",
			InstId:    "299",
			Removed:   "2016/03/14,01:15:00",
			Pins: []Pin{
				{
					PinNo:    0,
					Azimuth:  "0.0",
					Dip:      "-90.0",
					InstCode: "z",
					Reversed: "no",
					SeisCode: "EPI",
					StreamId: "WEL/20-HNZ/NZ",
				},
				{
					PinNo:    1,
					Azimuth:  "0.0",
					Dip:      "0.0",
					InstCode: "n",
					Reversed: "no",
					SeisCode: "EPI",
					StreamId: "WEL/20-HNN/NZ",
				},
				{
					PinNo:    2,
					Azimuth:  "90.0",
					Dip:      "0.0",
					InstCode: "e",
					Reversed: "no",
					SeisCode: "EPI",
					StreamId: "WEL/20-HNE/NZ",
				},
			},
		},
		{
			Installed: "2014/11/03,02:05:01",
			DevCode:   "Q33",
			InstId:    "299",
			Removed:   "2015/03/24,00:00:00",
			Pins: []Pin{
				{
					PinNo:    0,
					Azimuth:  "0.0",
					Dip:      "-90.0",
					InstCode: "z",
					Reversed: "no",
					SeisCode: "EPI",
					StreamId: "WEL/20-HNZ/NZ",
				},
				{
					PinNo:    1,
					Azimuth:  "0.0",
					Dip:      "0.0",
					InstCode: "n",
					Reversed: "no",
					SeisCode: "EPI",
					StreamId: "WEL/20-HNN/NZ",
				},
				{
					PinNo:    2,
					Azimuth:  "90.0",
					Dip:      "0.0",
					InstCode: "e",
					Reversed: "no",
					SeisCode: "EPI",
					StreamId: "WEL/20-HNE/NZ",
				},
			},
		},
		{
			Installed: "2016/03/14,01:15:01",
			DevCode:   "Q33",
			InstId:    "284",
			Removed:   "2016/12/19,21:00:00",
			Pins: []Pin{
				{
					PinNo:    0,
					Azimuth:  "0.0",
					Dip:      "-90.0",
					InstCode: "z",
					Reversed: "no",
					SeisCode: "EPI",
					StreamId: "WEL/20-HNZ/NZ",
				},
				{
					PinNo:    1,
					Azimuth:  "0.0",
					Dip:      "0.0",
					InstCode: "n",
					Reversed: "no",
					SeisCode: "EPI",
					StreamId: "WEL/20-HNN/NZ",
				},
				{
					PinNo:    2,
					Azimuth:  "90.0",
					Dip:      "0.0",
					InstCode: "e",
					Reversed: "no",
					SeisCode: "EPI",
					StreamId: "WEL/20-HNE/NZ",
				},
			},
		},
	},
	"PXZ": {
		{
			Installed: "2016-08-22T12:00:00",
			DevCode:   "Q33",
			InstId:    "368",
			Removed:   "2018/01/17,05:30:00",
			Pins: []Pin{
				{
					PinNo:    0,
					Azimuth:  "0.0",
					Dip:      "-90.0",
					InstCode: "z",
					Reversed: "no",
					SeisCode: "EPI",
					StreamId: "PXZ/20-HNZ/NZ",
				},
				{
					PinNo:    1,
					Azimuth:  "0.0",
					Dip:      "0.0",
					InstCode: "n",
					Reversed: "no",
					SeisCode: "EPI",
					StreamId: "PXZ/20-HNN/NZ",
				},
				{
					PinNo:    2,
					Azimuth:  "90.0",
					Dip:      "0.0",
					InstCode: "e",
					Reversed: "no",
					SeisCode: "EPI",
					StreamId: "PXZ/20-HNE/NZ",
				},
			},
		},
	},
	"JCZ": {
		{
			Installed: "2017-06-26T12:00:00",
			DevCode:   "Q33",
			InstId:    "367",
			Removed:   "2018-11-27T00:00:00",
			Pins: []Pin{
				{
					PinNo:    0,
					Azimuth:  "0.0",
					Dip:      "-90.0",
					InstCode: "z",
					Reversed: "no",
					SeisCode: "EPI",
					StreamId: "JCZ/20-HNZ/NZ",
				},
				{
					PinNo:    1,
					Azimuth:  "0.0",
					Dip:      "0.0",
					InstCode: "n",
					Reversed: "no",
					SeisCode: "EPI",
					StreamId: "JCZ/20-HNN/NZ",
				},
				{
					PinNo:    2,
					Azimuth:  "90.0",
					Dip:      "0.0",
					InstCode: "e",
					Reversed: "no",
					SeisCode: "EPI",
					StreamId: "JCZ/20-HNE/NZ",
				},
			},
		},
	},
}
