// Code generated by main. DO NOT EDIT.

package stationxml

import (
	"bytes"
	"encoding/xml"
	"time"
)

type AngleType struct {
	Value             float64 `xml:",chardata"`
	Unit              string  `xml:"unit,attr,omitempty"`
	PlusError         float64 `xml:"plusError,attr,omitempty"`
	MinusError        float64 `xml:"minusError,attr,omitempty"`
	MeasurementMethod string  `xml:"measurementMethod,attr,omitempty"`
}

// May be one of MACLAURIN
type ApproximationType string

// Instrument azimuth, degrees clockwise from North.
type AzimuthType struct {
	Value             float64 `xml:",chardata"`
	Unit              string  `xml:"unit,attr,omitempty"`
	PlusError         float64 `xml:"plusError,attr,omitempty"`
	MinusError        float64 `xml:"minusError,attr,omitempty"`
	MeasurementMethod string  `xml:"measurementMethod,attr,omitempty"`
}

// The BaseFilterType is derived by all filters.
type BaseFilterType struct {
	Items       []string  `xml:",any"`
	Description string    `xml:"http://www.fdsn.org/xml/station/1 Description,omitempty"`
	InputUnits  UnitsType `xml:"http://www.fdsn.org/xml/station/1 InputUnits"`
	OutputUnits UnitsType `xml:"http://www.fdsn.org/xml/station/1 OutputUnits"`
	ResourceId  string    `xml:"resourceId,attr,omitempty"`
	Name        string    `xml:"name,attr,omitempty"`
}

// A base node type for derivation from: Network, Station and Channel
// types.
type BaseNodeType struct {
	Items            []string             `xml:",any"`
	Description      string               `xml:"http://www.fdsn.org/xml/station/1 Description,omitempty"`
	Identifier       []IdentifierType     `xml:"http://www.fdsn.org/xml/station/1 Identifier,omitempty"`
	Comment          []CommentType        `xml:"http://www.fdsn.org/xml/station/1 Comment,omitempty"`
	DataAvailability DataAvailabilityType `xml:"http://www.fdsn.org/xml/station/1 DataAvailability,omitempty"`
	Code             string               `xml:"code,attr"`
	StartDate        time.Time            `xml:"startDate,attr,omitempty"`
	EndDate          time.Time            `xml:"endDate,attr,omitempty"`
	SourceID         string               `xml:"sourceID,attr,omitempty"`
	RestrictedStatus RestrictedStatusType `xml:"restrictedStatus,attr,omitempty"`
	AlternateCode    string               `xml:"alternateCode,attr,omitempty"`
	HistoricalCode   string               `xml:"historicalCode,attr,omitempty"`
}

func (t *BaseNodeType) MarshalXML(e *xml.Encoder, start xml.StartElement) error {
	type T BaseNodeType
	var layout struct {
		*T
		StartDate *xsdDateTime `xml:"startDate,attr,omitempty"`
		EndDate   *xsdDateTime `xml:"endDate,attr,omitempty"`
	}
	layout.T = (*T)(t)
	layout.StartDate = (*xsdDateTime)(&layout.T.StartDate)
	layout.EndDate = (*xsdDateTime)(&layout.T.EndDate)
	return e.EncodeElement(layout, start)
}
func (t *BaseNodeType) UnmarshalXML(d *xml.Decoder, start xml.StartElement) error {
	type T BaseNodeType
	var overlay struct {
		*T
		StartDate *xsdDateTime `xml:"startDate,attr,omitempty"`
		EndDate   *xsdDateTime `xml:"endDate,attr,omitempty"`
	}
	overlay.T = (*T)(t)
	overlay.StartDate = (*xsdDateTime)(&overlay.T.StartDate)
	overlay.EndDate = (*xsdDateTime)(&overlay.T.EndDate)
	return d.DecodeElement(&overlay, &start)
}

// May be one of ANALOG (RADIANS/SECOND), ANALOG (HERTZ), DIGITAL
type CfTransferFunctionType string

// Equivalent to SEED blockette 52 and parent element for the related the
// response blockettes.
type ChannelType struct {
	Items             []string                `xml:",any"`
	Description       string                  `xml:"http://www.fdsn.org/xml/station/1 Description,omitempty"`
	Identifier        []IdentifierType        `xml:"http://www.fdsn.org/xml/station/1 Identifier,omitempty"`
	Comment           []CommentType           `xml:"http://www.fdsn.org/xml/station/1 Comment,omitempty"`
	DataAvailability  DataAvailabilityType    `xml:"http://www.fdsn.org/xml/station/1 DataAvailability,omitempty"`
	ExternalReference []ExternalReferenceType `xml:"http://www.fdsn.org/xml/station/1 ExternalReference,omitempty"`
	Latitude          LatitudeType            `xml:"http://www.fdsn.org/xml/station/1 Latitude"`
	Longitude         LongitudeType           `xml:"http://www.fdsn.org/xml/station/1 Longitude"`
	Elevation         DistanceType            `xml:"http://www.fdsn.org/xml/station/1 Elevation"`
	Depth             DistanceType            `xml:"http://www.fdsn.org/xml/station/1 Depth"`
	Azimuth           AzimuthType             `xml:"http://www.fdsn.org/xml/station/1 Azimuth,omitempty"`
	Dip               DipType                 `xml:"http://www.fdsn.org/xml/station/1 Dip,omitempty"`
	WaterLevel        FloatType               `xml:"http://www.fdsn.org/xml/station/1 WaterLevel,omitempty"`
	Type              []Type                  `xml:"http://www.fdsn.org/xml/station/1 Type,omitempty"`
	SampleRate        SampleRateType          `xml:"http://www.fdsn.org/xml/station/1 SampleRate"`
	SampleRateRatio   SampleRateRatioType     `xml:"http://www.fdsn.org/xml/station/1 SampleRateRatio,omitempty"`
	ClockDrift        ClockDrift              `xml:"http://www.fdsn.org/xml/station/1 ClockDrift,omitempty"`
	CalibrationUnits  UnitsType               `xml:"http://www.fdsn.org/xml/station/1 CalibrationUnits,omitempty"`
	Sensor            EquipmentType           `xml:"http://www.fdsn.org/xml/station/1 Sensor,omitempty"`
	PreAmplifier      EquipmentType           `xml:"http://www.fdsn.org/xml/station/1 PreAmplifier,omitempty"`
	DataLogger        EquipmentType           `xml:"http://www.fdsn.org/xml/station/1 DataLogger,omitempty"`
	Equipment         []EquipmentType         `xml:"http://www.fdsn.org/xml/station/1 Equipment,omitempty"`
	Response          ResponseType            `xml:"http://www.fdsn.org/xml/station/1 Response,omitempty"`
	LocationCode      string                  `xml:"locationCode,attr"`
	Code              string                  `xml:"code,attr"`
	StartDate         time.Time               `xml:"startDate,attr,omitempty"`
	EndDate           time.Time               `xml:"endDate,attr,omitempty"`
	SourceID          string                  `xml:"sourceID,attr,omitempty"`
	RestrictedStatus  RestrictedStatusType    `xml:"restrictedStatus,attr,omitempty"`
	AlternateCode     string                  `xml:"alternateCode,attr,omitempty"`
	HistoricalCode    string                  `xml:"historicalCode,attr,omitempty"`
}

func (t *ChannelType) MarshalXML(e *xml.Encoder, start xml.StartElement) error {
	type T ChannelType
	var layout struct {
		*T
		StartDate *xsdDateTime `xml:"startDate,attr,omitempty"`
		EndDate   *xsdDateTime `xml:"endDate,attr,omitempty"`
	}
	layout.T = (*T)(t)
	layout.StartDate = (*xsdDateTime)(&layout.T.StartDate)
	layout.EndDate = (*xsdDateTime)(&layout.T.EndDate)
	return e.EncodeElement(layout, start)
}
func (t *ChannelType) UnmarshalXML(d *xml.Decoder, start xml.StartElement) error {
	type T ChannelType
	var overlay struct {
		*T
		StartDate *xsdDateTime `xml:"startDate,attr,omitempty"`
		EndDate   *xsdDateTime `xml:"endDate,attr,omitempty"`
	}
	overlay.T = (*T)(t)
	overlay.StartDate = (*xsdDateTime)(&overlay.T.StartDate)
	overlay.EndDate = (*xsdDateTime)(&overlay.T.EndDate)
	return d.DecodeElement(&overlay, &start)
}

type ClockDrift struct {
	Value             float64 `xml:",chardata"`
	Unit              string  `xml:"unit,attr,omitempty"`
	PlusError         float64 `xml:"plusError,attr,omitempty"`
	MinusError        float64 `xml:"minusError,attr,omitempty"`
	MeasurementMethod string  `xml:"measurementMethod,attr,omitempty"`
}

type Coefficient struct {
	Value             float64 `xml:",chardata"`
	Number            int     `xml:"number,attr,omitempty"`
	PlusError         float64 `xml:"plusError,attr,omitempty"`
	MinusError        float64 `xml:"minusError,attr,omitempty"`
	MeasurementMethod string  `xml:"measurementMethod,attr,omitempty"`
}

// Response: coefficients for FIR filter. Laplace transforms or IIR
// filters can be expressed using type as well but the PolesAndZerosType should be used
// instead. Corresponds to SEED blockette 54.
type CoefficientsType struct {
	Items                  []string               `xml:",any"`
	Description            string                 `xml:"http://www.fdsn.org/xml/station/1 Description,omitempty"`
	InputUnits             UnitsType              `xml:"http://www.fdsn.org/xml/station/1 InputUnits"`
	OutputUnits            UnitsType              `xml:"http://www.fdsn.org/xml/station/1 OutputUnits"`
	CfTransferFunctionType CfTransferFunctionType `xml:"http://www.fdsn.org/xml/station/1 CfTransferFunctionType"`
	Numerator              []Numerator            `xml:"http://www.fdsn.org/xml/station/1 Numerator,omitempty"`
	Denominator            []Denominator          `xml:"http://www.fdsn.org/xml/station/1 Denominator,omitempty"`
	ResourceId             string                 `xml:"resourceId,attr,omitempty"`
	Name                   string                 `xml:"name,attr,omitempty"`
}

// Container for a comment or log entry. Corresponds to SEED blockettes
// 31, 51 and 59.
type CommentType struct {
	Value              string       `xml:"http://www.fdsn.org/xml/station/1 Value"`
	BeginEffectiveTime time.Time    `xml:"http://www.fdsn.org/xml/station/1 BeginEffectiveTime,omitempty"`
	EndEffectiveTime   time.Time    `xml:"http://www.fdsn.org/xml/station/1 EndEffectiveTime,omitempty"`
	Author             []PersonType `xml:"http://www.fdsn.org/xml/station/1 Author,omitempty"`
	Id                 int          `xml:"id,attr,omitempty"`
	Subject            string       `xml:"subject,attr,omitempty"`
}

func (t *CommentType) MarshalXML(e *xml.Encoder, start xml.StartElement) error {
	type T CommentType
	var layout struct {
		*T
		BeginEffectiveTime *xsdDateTime `xml:"http://www.fdsn.org/xml/station/1 BeginEffectiveTime,omitempty"`
		EndEffectiveTime   *xsdDateTime `xml:"http://www.fdsn.org/xml/station/1 EndEffectiveTime,omitempty"`
	}
	layout.T = (*T)(t)
	layout.BeginEffectiveTime = (*xsdDateTime)(&layout.T.BeginEffectiveTime)
	layout.EndEffectiveTime = (*xsdDateTime)(&layout.T.EndEffectiveTime)
	return e.EncodeElement(layout, start)
}
func (t *CommentType) UnmarshalXML(d *xml.Decoder, start xml.StartElement) error {
	type T CommentType
	var overlay struct {
		*T
		BeginEffectiveTime *xsdDateTime `xml:"http://www.fdsn.org/xml/station/1 BeginEffectiveTime,omitempty"`
		EndEffectiveTime   *xsdDateTime `xml:"http://www.fdsn.org/xml/station/1 EndEffectiveTime,omitempty"`
	}
	overlay.T = (*T)(t)
	overlay.BeginEffectiveTime = (*xsdDateTime)(&overlay.T.BeginEffectiveTime)
	overlay.EndEffectiveTime = (*xsdDateTime)(&overlay.T.EndEffectiveTime)
	return d.DecodeElement(&overlay, &start)
}

// A type for describing data availability extents, the earliest and
// latest data available. No information is included about the continuity of the data
// is included or implied.
type DataAvailabilityExtentType struct {
	Start time.Time `xml:"start,attr"`
	End   time.Time `xml:"end,attr"`
}

func (t *DataAvailabilityExtentType) MarshalXML(e *xml.Encoder, start xml.StartElement) error {
	type T DataAvailabilityExtentType
	var layout struct {
		*T
		Start *xsdDateTime `xml:"start,attr"`
		End   *xsdDateTime `xml:"end,attr"`
	}
	layout.T = (*T)(t)
	layout.Start = (*xsdDateTime)(&layout.T.Start)
	layout.End = (*xsdDateTime)(&layout.T.End)
	return e.EncodeElement(layout, start)
}
func (t *DataAvailabilityExtentType) UnmarshalXML(d *xml.Decoder, start xml.StartElement) error {
	type T DataAvailabilityExtentType
	var overlay struct {
		*T
		Start *xsdDateTime `xml:"start,attr"`
		End   *xsdDateTime `xml:"end,attr"`
	}
	overlay.T = (*T)(t)
	overlay.Start = (*xsdDateTime)(&overlay.T.Start)
	overlay.End = (*xsdDateTime)(&overlay.T.End)
	return d.DecodeElement(&overlay, &start)
}

// A type for describing data availability spans, with variable
// continuity. The time range described may be based on the request parameters that
// generated the document and not necessarily relate to continuity outside of the
// range. It may also be a smaller time window than the request depending on the data
// characteristics.
type DataAvailabilitySpanType struct {
	Start           time.Time `xml:"start,attr"`
	End             time.Time `xml:"end,attr"`
	NumberSegments  int       `xml:"numberSegments,attr"`
	MaximumTimeTear float64   `xml:"maximumTimeTear,attr,omitempty"`
}

func (t *DataAvailabilitySpanType) MarshalXML(e *xml.Encoder, start xml.StartElement) error {
	type T DataAvailabilitySpanType
	var layout struct {
		*T
		Start *xsdDateTime `xml:"start,attr"`
		End   *xsdDateTime `xml:"end,attr"`
	}
	layout.T = (*T)(t)
	layout.Start = (*xsdDateTime)(&layout.T.Start)
	layout.End = (*xsdDateTime)(&layout.T.End)
	return e.EncodeElement(layout, start)
}
func (t *DataAvailabilitySpanType) UnmarshalXML(d *xml.Decoder, start xml.StartElement) error {
	type T DataAvailabilitySpanType
	var overlay struct {
		*T
		Start *xsdDateTime `xml:"start,attr"`
		End   *xsdDateTime `xml:"end,attr"`
	}
	overlay.T = (*T)(t)
	overlay.Start = (*xsdDateTime)(&overlay.T.Start)
	overlay.End = (*xsdDateTime)(&overlay.T.End)
	return d.DecodeElement(&overlay, &start)
}

// An type for describing data availability.
type DataAvailabilityType struct {
	Items  []string                   `xml:",any"`
	Extent DataAvailabilityExtentType `xml:"http://www.fdsn.org/xml/station/1 Extent,omitempty"`
	Span   []DataAvailabilitySpanType `xml:"http://www.fdsn.org/xml/station/1 Span,omitempty"`
}

// Corresponds to SEED blockette 57.
type DecimationType struct {
	InputSampleRate FrequencyType `xml:"http://www.fdsn.org/xml/station/1 InputSampleRate"`
	Factor          int           `xml:"http://www.fdsn.org/xml/station/1 Factor"`
	Offset          int           `xml:"http://www.fdsn.org/xml/station/1 Offset"`
	Delay           FloatType     `xml:"http://www.fdsn.org/xml/station/1 Delay"`
	Correction      FloatType     `xml:"http://www.fdsn.org/xml/station/1 Correction"`
}

type Denominator struct {
	Value             float64 `xml:",chardata"`
	Number            int     `xml:"number,attr,omitempty"`
	PlusError         float64 `xml:"plusError,attr,omitempty"`
	MinusError        float64 `xml:"minusError,attr,omitempty"`
	MeasurementMethod string  `xml:"measurementMethod,attr,omitempty"`
}

// Instrument dip in degrees down from horizontal. Together azimuth and
// dip describe the direction of the sensitive axis of the instrument.
type DipType struct {
	Value             float64 `xml:",chardata"`
	Unit              string  `xml:"unit,attr,omitempty"`
	PlusError         float64 `xml:"plusError,attr,omitempty"`
	MinusError        float64 `xml:"minusError,attr,omitempty"`
	MeasurementMethod string  `xml:"measurementMethod,attr,omitempty"`
}

// Extension of FloatType for distances, elevations, and
// depths.
type DistanceType struct {
	Value             float64 `xml:",chardata"`
	Unit              string  `xml:"unit,attr,omitempty"`
	PlusError         float64 `xml:"plusError,attr,omitempty"`
	MinusError        float64 `xml:"minusError,attr,omitempty"`
	MeasurementMethod string  `xml:"measurementMethod,attr,omitempty"`
}

// Must match the pattern [\w\.\-_]+@[\w\.\-_]+
type EmailType string

type EquipmentType struct {
	Items            []string    `xml:",any"`
	Type             string      `xml:"http://www.fdsn.org/xml/station/1 Type,omitempty"`
	Description      string      `xml:"http://www.fdsn.org/xml/station/1 Description,omitempty"`
	Manufacturer     string      `xml:"http://www.fdsn.org/xml/station/1 Manufacturer,omitempty"`
	Vendor           string      `xml:"http://www.fdsn.org/xml/station/1 Vendor,omitempty"`
	Model            string      `xml:"http://www.fdsn.org/xml/station/1 Model,omitempty"`
	SerialNumber     string      `xml:"http://www.fdsn.org/xml/station/1 SerialNumber,omitempty"`
	InstallationDate time.Time   `xml:"http://www.fdsn.org/xml/station/1 InstallationDate,omitempty"`
	RemovalDate      time.Time   `xml:"http://www.fdsn.org/xml/station/1 RemovalDate,omitempty"`
	CalibrationDate  []time.Time `xml:"http://www.fdsn.org/xml/station/1 CalibrationDate,omitempty"`
	ResourceId       string      `xml:"resourceId,attr,omitempty"`
}

func (t *EquipmentType) MarshalXML(e *xml.Encoder, start xml.StartElement) error {
	type T EquipmentType
	var layout struct {
		*T
		InstallationDate *xsdDateTime `xml:"http://www.fdsn.org/xml/station/1 InstallationDate,omitempty"`
		RemovalDate      *xsdDateTime `xml:"http://www.fdsn.org/xml/station/1 RemovalDate,omitempty"`
		CalibrationDate  *xsdDateTime `xml:"http://www.fdsn.org/xml/station/1 CalibrationDate,omitempty"`
	}
	layout.T = (*T)(t)
	layout.InstallationDate = (*xsdDateTime)(&layout.T.InstallationDate)
	layout.RemovalDate = (*xsdDateTime)(&layout.T.RemovalDate)
	layout.CalibrationDate = (*xsdDateTime)(&layout.T.CalibrationDate)
	return e.EncodeElement(layout, start)
}
func (t *EquipmentType) UnmarshalXML(d *xml.Decoder, start xml.StartElement) error {
	type T EquipmentType
	var overlay struct {
		*T
		InstallationDate *xsdDateTime `xml:"http://www.fdsn.org/xml/station/1 InstallationDate,omitempty"`
		RemovalDate      *xsdDateTime `xml:"http://www.fdsn.org/xml/station/1 RemovalDate,omitempty"`
		CalibrationDate  *xsdDateTime `xml:"http://www.fdsn.org/xml/station/1 CalibrationDate,omitempty"`
	}
	overlay.T = (*T)(t)
	overlay.InstallationDate = (*xsdDateTime)(&overlay.T.InstallationDate)
	overlay.RemovalDate = (*xsdDateTime)(&overlay.T.RemovalDate)
	overlay.CalibrationDate = (*xsdDateTime)(&overlay.T.CalibrationDate)
	return d.DecodeElement(&overlay, &start)
}

// This type contains a URI and description for external data that users
// may want to reference in StationXML.
type ExternalReferenceType struct {
	URI         string `xml:"http://www.fdsn.org/xml/station/1 URI"`
	Description string `xml:"http://www.fdsn.org/xml/station/1 Description"`
}

// Response: FIR filter. Corresponds to SEED blockette 61. FIR filters
// are also commonly documented using the CoefficientsType element.
type FIRType struct {
	Items                []string               `xml:",any"`
	Description          string                 `xml:"http://www.fdsn.org/xml/station/1 Description,omitempty"`
	InputUnits           UnitsType              `xml:"http://www.fdsn.org/xml/station/1 InputUnits"`
	OutputUnits          UnitsType              `xml:"http://www.fdsn.org/xml/station/1 OutputUnits"`
	Symmetry             Symmetry               `xml:"http://www.fdsn.org/xml/station/1 Symmetry"`
	NumeratorCoefficient []NumeratorCoefficient `xml:"http://www.fdsn.org/xml/station/1 NumeratorCoefficient,omitempty"`
	ResourceId           string                 `xml:"resourceId,attr,omitempty"`
	Name                 string                 `xml:"name,attr,omitempty"`
}

type FloatNoUnitType struct {
	Value             float64 `xml:",chardata"`
	PlusError         float64 `xml:"plusError,attr,omitempty"`
	MinusError        float64 `xml:"minusError,attr,omitempty"`
	MeasurementMethod string  `xml:"measurementMethod,attr,omitempty"`
}

// Representation of floating-point numbers used as
// measurements.
type FloatType struct {
	Value             float64 `xml:",chardata"`
	Unit              string  `xml:"unit,attr,omitempty"`
	PlusError         float64 `xml:"plusError,attr,omitempty"`
	MinusError        float64 `xml:"minusError,attr,omitempty"`
	MeasurementMethod string  `xml:"measurementMethod,attr,omitempty"`
}

type FrequencyType struct {
	Value             float64 `xml:",chardata"`
	Unit              string  `xml:"unit,attr,omitempty"`
	PlusError         float64 `xml:"plusError,attr,omitempty"`
	MinusError        float64 `xml:"minusError,attr,omitempty"`
	MeasurementMethod string  `xml:"measurementMethod,attr,omitempty"`
}

// Complex type for sensitivity and frequency ranges. This complex type
// can be used to represent both overall sensitivities and individual stage gains. The
// FrequencyRangeGroup is an optional construct that defines a pass band in Hertz (
// FrequencyStart and FrequencyEnd) in which the SensitivityValue is valid within the
// number of decibels specified in FrequencyDBVariation.
type GainType struct {
	Value     float64 `xml:"http://www.fdsn.org/xml/station/1 Value"`
	Frequency float64 `xml:"http://www.fdsn.org/xml/station/1 Frequency"`
}

// A type to document persistent identifiers.
// Identifier values should be specified without a URI scheme (prefix),
// instead the identifer type is documented as an attribute.
type IdentifierType struct {
	Value string `xml:",chardata"`
	Type  string `xml:"type,attr,omitempty"`
}

// Base latitude type. Because of the limitations of schema, defining
// this type and then extending it to create the real latitude type is the only way to
// restrict values while adding datum as an attribute.
type LatitudeBaseType struct {
	Value             float64 `xml:",chardata"`
	Unit              string  `xml:"unit,attr,omitempty"`
	PlusError         float64 `xml:"plusError,attr,omitempty"`
	MinusError        float64 `xml:"minusError,attr,omitempty"`
	MeasurementMethod string  `xml:"measurementMethod,attr,omitempty"`
}

// Type for latitude coordinate.
type LatitudeType struct {
	Value             float64 `xml:",chardata"`
	Datum             string  `xml:"datum,attr,omitempty"`
	Unit              string  `xml:"unit,attr,omitempty"`
	PlusError         float64 `xml:"plusError,attr,omitempty"`
	MinusError        float64 `xml:"minusError,attr,omitempty"`
	MeasurementMethod string  `xml:"measurementMethod,attr,omitempty"`
}

func (t *LatitudeType) UnmarshalXML(d *xml.Decoder, start xml.StartElement) error {
	type T LatitudeType
	var overlay struct {
		*T
		Datum *string `xml:"datum,attr,omitempty"`
	}
	overlay.T = (*T)(t)
	overlay.Datum = (*string)(&overlay.T.Datum)
	return d.DecodeElement(&overlay, &start)
}

type LongitudeBaseType struct {
	Value             float64 `xml:",chardata"`
	Unit              string  `xml:"unit,attr,omitempty"`
	PlusError         float64 `xml:"plusError,attr,omitempty"`
	MinusError        float64 `xml:"minusError,attr,omitempty"`
	MeasurementMethod string  `xml:"measurementMethod,attr,omitempty"`
}

// Type for longitude coordinate.
type LongitudeType struct {
	Value             float64 `xml:",chardata"`
	Datum             string  `xml:"datum,attr,omitempty"`
	Unit              string  `xml:"unit,attr,omitempty"`
	PlusError         float64 `xml:"plusError,attr,omitempty"`
	MinusError        float64 `xml:"minusError,attr,omitempty"`
	MeasurementMethod string  `xml:"measurementMethod,attr,omitempty"`
}

func (t *LongitudeType) UnmarshalXML(d *xml.Decoder, start xml.StartElement) error {
	type T LongitudeType
	var overlay struct {
		*T
		Datum *string `xml:"datum,attr,omitempty"`
	}
	overlay.T = (*T)(t)
	overlay.Datum = (*string)(&overlay.T.Datum)
	return d.DecodeElement(&overlay, &start)
}

// This type represents the Network layer, all station metadata is
// contained within this element. The official name of the network or other descriptive
// information can be included in the Description element. The Network can contain 0 or
// more Stations.
type NetworkType struct {
	Items                  []string             `xml:",any"`
	Description            string               `xml:"http://www.fdsn.org/xml/station/1 Description,omitempty"`
	Identifier             []IdentifierType     `xml:"http://www.fdsn.org/xml/station/1 Identifier,omitempty"`
	Comment                []CommentType        `xml:"http://www.fdsn.org/xml/station/1 Comment,omitempty"`
	DataAvailability       DataAvailabilityType `xml:"http://www.fdsn.org/xml/station/1 DataAvailability,omitempty"`
	Operator               []OperatorType       `xml:"http://www.fdsn.org/xml/station/1 Operator,omitempty"`
	TotalNumberStations    int                  `xml:"http://www.fdsn.org/xml/station/1 TotalNumberStations,omitempty"`
	SelectedNumberStations int                  `xml:"http://www.fdsn.org/xml/station/1 SelectedNumberStations,omitempty"`
	Station                []StationType        `xml:"http://www.fdsn.org/xml/station/1 Station,omitempty"`
	Code                   string               `xml:"code,attr"`
	StartDate              time.Time            `xml:"startDate,attr,omitempty"`
	EndDate                time.Time            `xml:"endDate,attr,omitempty"`
	SourceID               string               `xml:"sourceID,attr,omitempty"`
	RestrictedStatus       RestrictedStatusType `xml:"restrictedStatus,attr,omitempty"`
	AlternateCode          string               `xml:"alternateCode,attr,omitempty"`
	HistoricalCode         string               `xml:"historicalCode,attr,omitempty"`
}

func (t *NetworkType) MarshalXML(e *xml.Encoder, start xml.StartElement) error {
	type T NetworkType
	var layout struct {
		*T
		StartDate *xsdDateTime `xml:"startDate,attr,omitempty"`
		EndDate   *xsdDateTime `xml:"endDate,attr,omitempty"`
	}
	layout.T = (*T)(t)
	layout.StartDate = (*xsdDateTime)(&layout.T.StartDate)
	layout.EndDate = (*xsdDateTime)(&layout.T.EndDate)
	return e.EncodeElement(layout, start)
}
func (t *NetworkType) UnmarshalXML(d *xml.Decoder, start xml.StartElement) error {
	type T NetworkType
	var overlay struct {
		*T
		StartDate *xsdDateTime `xml:"startDate,attr,omitempty"`
		EndDate   *xsdDateTime `xml:"endDate,attr,omitempty"`
	}
	overlay.T = (*T)(t)
	overlay.StartDate = (*xsdDateTime)(&overlay.T.StartDate)
	overlay.EndDate = (*xsdDateTime)(&overlay.T.EndDate)
	return d.DecodeElement(&overlay, &start)
}

// May be one of NOMINAL, CALCULATED
type NominalType string

type Numerator struct {
	Value             float64 `xml:",chardata"`
	Number            int     `xml:"number,attr,omitempty"`
	PlusError         float64 `xml:"plusError,attr,omitempty"`
	MinusError        float64 `xml:"minusError,attr,omitempty"`
	MeasurementMethod string  `xml:"measurementMethod,attr,omitempty"`
}

type NumeratorCoefficient struct {
	Value float64 `xml:",chardata"`
	I     int     `xml:"i,attr,omitempty"`
}

// An operating agency and associated contact persons.
// Since the Contact element is a generic type that represents any contact
// person, it also has its own optional Agency element.
// It is expected that typically the contact’s optional Agency tag will match the Operator Agency.
// Only contacts appropriate for the enclosing element should be include in the Operator tag.
type OperatorType struct {
	Agency  string       `xml:"http://www.fdsn.org/xml/station/1 Agency"`
	Contact []PersonType `xml:"http://www.fdsn.org/xml/station/1 Contact,omitempty"`
	WebSite string       `xml:"http://www.fdsn.org/xml/station/1 WebSite,omitempty"`
}

// Representation of a person's contact information. A person can belong
// to multiple agencies and have multiple email addresses and phone
// numbers.
type PersonType struct {
	Name   []string          `xml:"http://www.fdsn.org/xml/station/1 Name,omitempty"`
	Agency []string          `xml:"http://www.fdsn.org/xml/station/1 Agency,omitempty"`
	Email  []EmailType       `xml:"http://www.fdsn.org/xml/station/1 Email,omitempty"`
	Phone  []PhoneNumberType `xml:"http://www.fdsn.org/xml/station/1 Phone,omitempty"`
}

// Must match the pattern [0-9]+-[0-9]+
type PhoneNumber string

type PhoneNumberType struct {
	CountryCode int         `xml:"http://www.fdsn.org/xml/station/1 CountryCode,omitempty"`
	AreaCode    int         `xml:"http://www.fdsn.org/xml/station/1 AreaCode"`
	PhoneNumber PhoneNumber `xml:"http://www.fdsn.org/xml/station/1 PhoneNumber"`
	Description string      `xml:"description,attr,omitempty"`
}

// Complex numbers used as poles or zeros in channel
// response.
type PoleZeroType struct {
	Real      FloatNoUnitType `xml:"http://www.fdsn.org/xml/station/1 Real"`
	Imaginary FloatNoUnitType `xml:"http://www.fdsn.org/xml/station/1 Imaginary"`
	Number    int             `xml:"number,attr,omitempty"`
}

// Response: complex poles and zeros. Corresponds to SEED blockette
// 53.
type PolesZerosType struct {
	Items                  []string               `xml:",any"`
	Description            string                 `xml:"http://www.fdsn.org/xml/station/1 Description,omitempty"`
	InputUnits             UnitsType              `xml:"http://www.fdsn.org/xml/station/1 InputUnits"`
	OutputUnits            UnitsType              `xml:"http://www.fdsn.org/xml/station/1 OutputUnits"`
	PzTransferFunctionType PzTransferFunctionType `xml:"http://www.fdsn.org/xml/station/1 PzTransferFunctionType"`
	NormalizationFactor    float64                `xml:"http://www.fdsn.org/xml/station/1 NormalizationFactor,omitempty"`
	NormalizationFrequency FrequencyType          `xml:"http://www.fdsn.org/xml/station/1 NormalizationFrequency"`
	Zero                   []PoleZeroType         `xml:"http://www.fdsn.org/xml/station/1 Zero,omitempty"`
	Pole                   []PoleZeroType         `xml:"http://www.fdsn.org/xml/station/1 Pole,omitempty"`
	ResourceId             string                 `xml:"resourceId,attr,omitempty"`
	Name                   string                 `xml:"name,attr,omitempty"`
}

func (t *PolesZerosType) UnmarshalXML(d *xml.Decoder, start xml.StartElement) error {
	type T PolesZerosType
	var overlay struct {
		*T
		NormalizationFactor *float64 `xml:"http://www.fdsn.org/xml/station/1 NormalizationFactor,omitempty"`
	}
	overlay.T = (*T)(t)
	overlay.NormalizationFactor = (*float64)(&overlay.T.NormalizationFactor)
	return d.DecodeElement(&overlay, &start)
}

// Response: expressed as a polynomial (allows non-linear sensors to be
// described). Corresponds to SEED blockette 62. Can be used to describe a stage of
// acquisition or a complete system.
type PolynomialType struct {
	Items                   []string          `xml:",any"`
	Description             string            `xml:"http://www.fdsn.org/xml/station/1 Description,omitempty"`
	InputUnits              UnitsType         `xml:"http://www.fdsn.org/xml/station/1 InputUnits"`
	OutputUnits             UnitsType         `xml:"http://www.fdsn.org/xml/station/1 OutputUnits"`
	ApproximationType       ApproximationType `xml:"http://www.fdsn.org/xml/station/1 ApproximationType,omitempty"`
	FrequencyLowerBound     FrequencyType     `xml:"http://www.fdsn.org/xml/station/1 FrequencyLowerBound"`
	FrequencyUpperBound     FrequencyType     `xml:"http://www.fdsn.org/xml/station/1 FrequencyUpperBound"`
	ApproximationLowerBound float64           `xml:"http://www.fdsn.org/xml/station/1 ApproximationLowerBound"`
	ApproximationUpperBound float64           `xml:"http://www.fdsn.org/xml/station/1 ApproximationUpperBound"`
	MaximumError            float64           `xml:"http://www.fdsn.org/xml/station/1 MaximumError"`
	Coefficient             []Coefficient     `xml:"http://www.fdsn.org/xml/station/1 Coefficient"`
	ResourceId              string            `xml:"resourceId,attr,omitempty"`
	Name                    string            `xml:"name,attr,omitempty"`
}

func (t *PolynomialType) UnmarshalXML(d *xml.Decoder, start xml.StartElement) error {
	type T PolynomialType
	var overlay struct {
		*T
		ApproximationType *ApproximationType `xml:"http://www.fdsn.org/xml/station/1 ApproximationType,omitempty"`
	}
	overlay.T = (*T)(t)
	overlay.ApproximationType = (*ApproximationType)(&overlay.T.ApproximationType)
	return d.DecodeElement(&overlay, &start)
}

// May be one of LAPLACE (RADIANS/SECOND), LAPLACE (HERTZ), DIGITAL (Z-TRANSFORM)
type PzTransferFunctionType string

type ResponseListElementType struct {
	Frequency FrequencyType `xml:"http://www.fdsn.org/xml/station/1 Frequency"`
	Amplitude FloatType     `xml:"http://www.fdsn.org/xml/station/1 Amplitude"`
	Phase     AngleType     `xml:"http://www.fdsn.org/xml/station/1 Phase"`
}

// Response: list of frequency, amplitude and phase values. Corresponds
// to SEED blockette 55.
type ResponseListType struct {
	Items               []string                  `xml:",any"`
	Description         string                    `xml:"http://www.fdsn.org/xml/station/1 Description,omitempty"`
	InputUnits          UnitsType                 `xml:"http://www.fdsn.org/xml/station/1 InputUnits"`
	OutputUnits         UnitsType                 `xml:"http://www.fdsn.org/xml/station/1 OutputUnits"`
	ResponseListElement []ResponseListElementType `xml:"http://www.fdsn.org/xml/station/1 ResponseListElement,omitempty"`
	ResourceId          string                    `xml:"resourceId,attr,omitempty"`
	Name                string                    `xml:"name,attr,omitempty"`
}

// This complex type represents channel response and covers SEED
// blockettes 53 to 56.
type ResponseStageType struct {
	Items        []string         `xml:",any"`
	PolesZeros   PolesZerosType   `xml:"http://www.fdsn.org/xml/station/1 PolesZeros,omitempty"`
	Coefficients CoefficientsType `xml:"http://www.fdsn.org/xml/station/1 Coefficients,omitempty"`
	ResponseList ResponseListType `xml:"http://www.fdsn.org/xml/station/1 ResponseList,omitempty"`
	FIR          FIRType          `xml:"http://www.fdsn.org/xml/station/1 FIR,omitempty"`
	Decimation   DecimationType   `xml:"http://www.fdsn.org/xml/station/1 Decimation,omitempty"`
	StageGain    GainType         `xml:"http://www.fdsn.org/xml/station/1 StageGain,omitempty"`
	Polynomial   PolynomialType   `xml:"http://www.fdsn.org/xml/station/1 Polynomial,omitempty"`
	Number       int              `xml:"number,attr"`
	ResourceId   string           `xml:"resourceId,attr,omitempty"`
}

type ResponseType struct {
	Items                 []string            `xml:",any"`
	InstrumentSensitivity SensitivityType     `xml:"http://www.fdsn.org/xml/station/1 InstrumentSensitivity,omitempty"`
	InstrumentPolynomial  PolynomialType      `xml:"http://www.fdsn.org/xml/station/1 InstrumentPolynomial,omitempty"`
	Stage                 []ResponseStageType `xml:"http://www.fdsn.org/xml/station/1 Stage,omitempty"`
	ResourceId            string              `xml:"resourceId,attr,omitempty"`
}

// May be one of open, closed, partial
type RestrictedStatusType string

// Top-level type for Station XML. Required fields are Source (network ID
// of the institution sending the message), Created (creation time of the document)
// and one or more Network containers.
type RootType struct {
	Items         []string      `xml:",any"`
	Source        string        `xml:"http://www.fdsn.org/xml/station/1 Source"`
	Sender        string        `xml:"http://www.fdsn.org/xml/station/1 Sender,omitempty"`
	Module        string        `xml:"http://www.fdsn.org/xml/station/1 Module,omitempty"`
	ModuleURI     string        `xml:"http://www.fdsn.org/xml/station/1 ModuleURI,omitempty"`
	Created       time.Time     `xml:"http://www.fdsn.org/xml/station/1 Created"`
	Network       []NetworkType `xml:"http://www.fdsn.org/xml/station/1 Network"`
	SchemaVersion float64       `xml:"schemaVersion,attr"`
}

func (t *RootType) MarshalXML(e *xml.Encoder, start xml.StartElement) error {
	type T RootType
	var layout struct {
		*T
		Created *xsdDateTime `xml:"http://www.fdsn.org/xml/station/1 Created"`
	}
	layout.T = (*T)(t)
	layout.Created = (*xsdDateTime)(&layout.T.Created)
	return e.EncodeElement(layout, start)
}
func (t *RootType) UnmarshalXML(d *xml.Decoder, start xml.StartElement) error {
	type T RootType
	var overlay struct {
		*T
		Created *xsdDateTime `xml:"http://www.fdsn.org/xml/station/1 Created"`
	}
	overlay.T = (*T)(t)
	overlay.Created = (*xsdDateTime)(&overlay.T.Created)
	return d.DecodeElement(&overlay, &start)
}

// Sample rate expressed as number of samples in a number of
// seconds.
type SampleRateRatioType struct {
	NumberSamples int `xml:"http://www.fdsn.org/xml/station/1 NumberSamples"`
	NumberSeconds int `xml:"http://www.fdsn.org/xml/station/1 NumberSeconds"`
}

// Sample rate in samples per second.
type SampleRateType struct {
	Value             float64 `xml:",chardata"`
	Unit              string  `xml:"unit,attr,omitempty"`
	PlusError         float64 `xml:"plusError,attr,omitempty"`
	MinusError        float64 `xml:"minusError,attr,omitempty"`
	MeasurementMethod string  `xml:"measurementMethod,attr,omitempty"`
}

// A time value in seconds.
type SecondType struct {
	Value             float64 `xml:",chardata"`
	Unit              string  `xml:"unit,attr,omitempty"`
	PlusError         float64 `xml:"plusError,attr,omitempty"`
	MinusError        float64 `xml:"minusError,attr,omitempty"`
	MeasurementMethod string  `xml:"measurementMethod,attr,omitempty"`
}

// Sensitivity and frequency ranges. The FrequencyRangeGroup is an
// optional construct that defines a pass band in Hertz (FrequencyStart and
// FrequencyEnd) in which the SensitivityValue is valid within the number of decibels
// specified in FrequencyDBVariation.
type SensitivityType struct {
	Value                float64   `xml:"http://www.fdsn.org/xml/station/1 Value"`
	Frequency            float64   `xml:"http://www.fdsn.org/xml/station/1 Frequency"`
	InputUnits           UnitsType `xml:"http://www.fdsn.org/xml/station/1 InputUnits"`
	OutputUnits          UnitsType `xml:"http://www.fdsn.org/xml/station/1 OutputUnits"`
	FrequencyStart       float64   `xml:"http://www.fdsn.org/xml/station/1 FrequencyStart"`
	FrequencyEnd         float64   `xml:"http://www.fdsn.org/xml/station/1 FrequencyEnd"`
	FrequencyDBVariation float64   `xml:"http://www.fdsn.org/xml/station/1 FrequencyDBVariation"`
}

// Description of a site location using name and optional geopolitical
// boundaries (country, city, etc.).
type SiteType struct {
	Items       []string `xml:",any"`
	Name        string   `xml:"http://www.fdsn.org/xml/station/1 Name"`
	Description string   `xml:"http://www.fdsn.org/xml/station/1 Description,omitempty"`
	Town        string   `xml:"http://www.fdsn.org/xml/station/1 Town,omitempty"`
	County      string   `xml:"http://www.fdsn.org/xml/station/1 County,omitempty"`
	Region      string   `xml:"http://www.fdsn.org/xml/station/1 Region,omitempty"`
	Country     string   `xml:"http://www.fdsn.org/xml/station/1 Country,omitempty"`
}

// This type represents a Station epoch. It is common to only have a
// single station epoch with the station's creation and termination dates as the epoch
// start and end dates.
type StationType struct {
	Items                  []string                `xml:",any"`
	Description            string                  `xml:"http://www.fdsn.org/xml/station/1 Description,omitempty"`
	Identifier             []IdentifierType        `xml:"http://www.fdsn.org/xml/station/1 Identifier,omitempty"`
	Comment                []CommentType           `xml:"http://www.fdsn.org/xml/station/1 Comment,omitempty"`
	DataAvailability       DataAvailabilityType    `xml:"http://www.fdsn.org/xml/station/1 DataAvailability,omitempty"`
	Latitude               LatitudeType            `xml:"http://www.fdsn.org/xml/station/1 Latitude"`
	Longitude              LongitudeType           `xml:"http://www.fdsn.org/xml/station/1 Longitude"`
	Elevation              DistanceType            `xml:"http://www.fdsn.org/xml/station/1 Elevation"`
	Site                   SiteType                `xml:"http://www.fdsn.org/xml/station/1 Site"`
	WaterLevel             FloatType               `xml:"http://www.fdsn.org/xml/station/1 WaterLevel,omitempty"`
	Vault                  string                  `xml:"http://www.fdsn.org/xml/station/1 Vault,omitempty"`
	Geology                string                  `xml:"http://www.fdsn.org/xml/station/1 Geology,omitempty"`
	Equipment              []EquipmentType         `xml:"http://www.fdsn.org/xml/station/1 Equipment,omitempty"`
	Operator               []OperatorType          `xml:"http://www.fdsn.org/xml/station/1 Operator,omitempty"`
	CreationDate           time.Time               `xml:"http://www.fdsn.org/xml/station/1 CreationDate,omitempty"`
	TerminationDate        time.Time               `xml:"http://www.fdsn.org/xml/station/1 TerminationDate,omitempty"`
	TotalNumberChannels    int                     `xml:"http://www.fdsn.org/xml/station/1 TotalNumberChannels,omitempty"`
	SelectedNumberChannels int                     `xml:"http://www.fdsn.org/xml/station/1 SelectedNumberChannels,omitempty"`
	ExternalReference      []ExternalReferenceType `xml:"http://www.fdsn.org/xml/station/1 ExternalReference,omitempty"`
	Channel                []ChannelType           `xml:"http://www.fdsn.org/xml/station/1 Channel,omitempty"`
	Code                   string                  `xml:"code,attr"`
	StartDate              time.Time               `xml:"startDate,attr,omitempty"`
	EndDate                time.Time               `xml:"endDate,attr,omitempty"`
	SourceID               string                  `xml:"sourceID,attr,omitempty"`
	RestrictedStatus       RestrictedStatusType    `xml:"restrictedStatus,attr,omitempty"`
	AlternateCode          string                  `xml:"alternateCode,attr,omitempty"`
	HistoricalCode         string                  `xml:"historicalCode,attr,omitempty"`
}

func (t *StationType) MarshalXML(e *xml.Encoder, start xml.StartElement) error {
	type T StationType
	var layout struct {
		*T
		CreationDate    *xsdDateTime `xml:"http://www.fdsn.org/xml/station/1 CreationDate,omitempty"`
		TerminationDate *xsdDateTime `xml:"http://www.fdsn.org/xml/station/1 TerminationDate,omitempty"`
		StartDate       *xsdDateTime `xml:"startDate,attr,omitempty"`
		EndDate         *xsdDateTime `xml:"endDate,attr,omitempty"`
	}
	layout.T = (*T)(t)
	layout.CreationDate = (*xsdDateTime)(&layout.T.CreationDate)
	layout.TerminationDate = (*xsdDateTime)(&layout.T.TerminationDate)
	layout.StartDate = (*xsdDateTime)(&layout.T.StartDate)
	layout.EndDate = (*xsdDateTime)(&layout.T.EndDate)
	return e.EncodeElement(layout, start)
}
func (t *StationType) UnmarshalXML(d *xml.Decoder, start xml.StartElement) error {
	type T StationType
	var overlay struct {
		*T
		CreationDate    *xsdDateTime `xml:"http://www.fdsn.org/xml/station/1 CreationDate,omitempty"`
		TerminationDate *xsdDateTime `xml:"http://www.fdsn.org/xml/station/1 TerminationDate,omitempty"`
		StartDate       *xsdDateTime `xml:"startDate,attr,omitempty"`
		EndDate         *xsdDateTime `xml:"endDate,attr,omitempty"`
	}
	overlay.T = (*T)(t)
	overlay.CreationDate = (*xsdDateTime)(&overlay.T.CreationDate)
	overlay.TerminationDate = (*xsdDateTime)(&overlay.T.TerminationDate)
	overlay.StartDate = (*xsdDateTime)(&overlay.T.StartDate)
	overlay.EndDate = (*xsdDateTime)(&overlay.T.EndDate)
	return d.DecodeElement(&overlay, &start)
}

// May be one of NONE, EVEN, ODD
type Symmetry string

// May be one of TRIGGERED, CONTINUOUS, HEALTH, GEOPHYSICAL, WEATHER, FLAG, SYNTHESIZED, INPUT, EXPERIMENTAL, MAINTENANCE, BEAM
type Type string

// A type to document units. Corresponds to SEED blockette
// 34.
type UnitsType struct {
	Name        string `xml:"http://www.fdsn.org/xml/station/1 Name"`
	Description string `xml:"http://www.fdsn.org/xml/station/1 Description,omitempty"`
}

type VoltageType struct {
	Value             float64 `xml:",chardata"`
	Unit              string  `xml:"unit,attr,omitempty"`
	PlusError         float64 `xml:"plusError,attr,omitempty"`
	MinusError        float64 `xml:"minusError,attr,omitempty"`
	MeasurementMethod string  `xml:"measurementMethod,attr,omitempty"`
}

type xsdDateTime time.Time

func (t *xsdDateTime) UnmarshalText(text []byte) error {
	return _unmarshalTime(text, (*time.Time)(t), "2006-01-02T15:04:05.999999999")
}
func (t xsdDateTime) MarshalText() ([]byte, error) {
	return _marshalTime((time.Time)(t), "2006-01-02T15:04:05.999999999")
}
func (t xsdDateTime) MarshalXML(e *xml.Encoder, start xml.StartElement) error {
	if (time.Time)(t).IsZero() {
		return nil
	}
	m, err := t.MarshalText()
	if err != nil {
		return err
	}
	return e.EncodeElement(m, start)
}
func (t xsdDateTime) MarshalXMLAttr(name xml.Name) (xml.Attr, error) {
	if (time.Time)(t).IsZero() {
		return xml.Attr{}, nil
	}
	m, err := t.MarshalText()
	return xml.Attr{Name: name, Value: string(m)}, err
}
func _unmarshalTime(text []byte, t *time.Time, format string) (err error) {
	s := string(bytes.TrimSpace(text))
	*t, err = time.Parse(format, s)
	if _, ok := err.(*time.ParseError); ok {
		*t, err = time.Parse(format+"Z07:00", s)
	}
	return err
}
func _marshalTime(t time.Time, format string) ([]byte, error) {
	return []byte(t.Format(format + "Z07:00")), nil
}
