---

# https://igscb.jpl.nasa.gov/igscb/station/general/antenna.gra

AOAD/M_T: |2+
                             -----
                         /           \
                        |             |
      +-------------------------------------------------+     <--  0.1020  TCR
      |                                                 |
      |                                                 |
      |                                                 |
      |                                                 |
    +-+-------------------------------------------------+-+   <--  0.0380
    +-------------------+-------------+-------------------+   <--  0.0350  BCR
                        |             |
                       =|             |
                        +------x------+                       <--  0.0000  BPA=ARP
                                                                           RXC=NRP
    <--                      0.3810                     -->
ASH701945B_M: |2+
                           +-------+
                         /           \
                        |             |
      +-----------------+-------------+-----------------+     <--  0.1006  TCR
      |                                                 |
      |                                                 |
      |                                                 |
      |                                                 |
    +-+-------------------------------------------------+-+   <--  0.0376
    +-------------------+-------------+-------------------+   <--  0.0346  BCR
                        |             |
                        |             |
                        +------x------+                       <--  0.0000  BPA=ARP
                                                                           NOM=NRP
    <--                      0.3794                     -->
ASH700936B_M: |2+
                             -----
                         /           \
                        |             |
      +-------------------------------------------------+     <--  0.1020  TCR
      |                                                 |
      |                                                 |
      |                                                 |
      |                                                 |
    +-+-------------------------------------------------+-+   <--  0.0380
    +-------------------+-------------+-------------------+   <--  0.0350  BCR
                        |             |
                       =|             |
                        +------x------+                       <--  0.0000  BPA=ARP
                                                                           NOM=NRP
    <--                      0.3810                     -->
ASH700936C_M: |2+
                             -----
                         /           \
                        |             |
      +-------------------------------------------------+     <--  0.1020  TCR
      |                                                 |
      |                                                 |
      |                                                 |
      |                                                 |
    +-+-------------------------------------------------+-+   <--  0.0380
    +-------------------+-------------+-------------------+   <--  0.0350  BCR
                        |             |
                       =|             |
                        +------x------+                       <--  0.0000  BPA=ARP
                                                                           NOM=NRP
    <--                      0.3810                     -->
ASH700936D_M: |2+
                             -----
                         /           \
                        |             |
      +-------------------------------------------------+     <--  0.1020  TCR
      |                                                 |
      |                                                 |
      |                                                 |
      |                                                 |
    +-+-------------------------------------------------+-+   <--  0.0380
    +-------------------+-------------+-------------------+   <--  0.0350  BCR
                        |             |
                       =|             |
                        +------x------+                       <--  0.0000  BPA=ARP
                                                                           NOM=NRP
    <--                      0.3810                     -->
ASH700936E: |2+
                          +---------+
                         /           \
                        |             |
      +-----------------+-------------+-----------------+     <--  0.1008  TCR
      |                                                 |
      |                                                 |
      |                                                 |
      |                                                 |
    +-+-------------------------------------------------+-+   <--  0.0378
    +-------------------+-------------+-------------------+   <--  0.0348  BCR
                        |             |
                        |             |
                        +------x------+                       <--  0.0000  BPA=ARP
                                                                           NOM=NRP
    <--                      0.3794                     -->
ASH701933C_M: |2+
                          +---------+
                         /           \
                        |             |
      +-----------------+-------------+-----------------+     <--  0.1008  TCR
      |                                                 |
      |                                                 |
      |                                                 |
      |                                                 |
    +-+-------------------------------------------------+-+   <--  0.0378
    +-------------------+-------------+-------------------+   <--  0.0348  BCR
                        |             |
                        |             |
                        +------x------+                       <--  0.0000  BPA=ARP
                                                                           NOM=NRP
    <--                      0.3794                     -->
ASH701945E_M: |2+
                           +-------+
                         /           \
                        |             |
      +-----------------+-------------+-----------------+     <--  0.1006  TCR
      |                                                 |
      |                                                 |
      |                                                 |
      |                                                 |
    +-+-------------------------------------------------+-+   <--  0.0376
    +-------------------+-------------+-------------------+   <--  0.0346  BCR
                        |             |
                        |             |
                        +------x------+                       <--  0.0000  BPA=ARP
                                                                           NOM=NRP
    <--                      0.3794                     -->
LEIAT504: |2+
                           +-------+                          <--  0.1393
                         /           \
                        |             |
      +-----------------+-------------+-----------------+     <--  0.1012  TCR
      |                                                 |
      |                                                 |
      |                                                 |
      |                                                 |
    +-+-------------------------------------------------+-+   <--  0.0378
    +-------------------+-------------+-------------------+   <--  0.0345  BCR
                        |             |
                        |             |
                        +------x------+                       <--  0.0000  BPA=ARP
                                                                           NOM=NRP
    <--                      0.3794                     -->
TRM22020.00+GP: |2+
                           ----^----
                        /             \
    ++----------------+-----------------+----------------++   <--  0.0591  TGP
    ++---------------+-------------------+---------------++   <--  0.0556  BGP
                     |                   |
                      |                 |
                       |               |
                        +------x------+                       <--  0.0000  BPA=ARP
                                                                           NOM=NRP
     <--                     0.4668                    -->                 Notches
    <--                      0.4826                     -->                Edge
TRM29659.00: |2+
                             -----
                         /           \
                        |             |
      +-------------------------------------------------+     <--  0.1020  TCR
      |                                                 |
      |                                                 |
      |                                                 |
      |                                                 |
    +-+-------------------------------------------------+-+   <--  0.0381
    +-------------------+-------------+-------------------+   <--  0.0350  BCR
                        |             |
                       =|             |
                        +------x------+                       <--  0.0000  BPA=ARP
                                                                           RXC=NRP
    <--                      0.3810                     -->
TRM33429.20+GP: |2+
                           ----^----
                        /             \
    ++----------------+-----------------+----------------++   <--  0.0631  TGP
    ++---------------+-------------------+---------------++   <--  0.0596  BGP
                     |                   |
                     |                   |
                      |                 |
                       +-------x-------+                      <--  0.0000  BPA=ARP
                                                                           NOM=NRP
     <--                     0.4668                    -->                 Notches
    <--                      0.4826                     -->                Edge
TRM41249.00: |2+
     / --------------------------------------------- \
    +                                                 +
     \ --------------------------------------------- /
                     \               /
                      \             /
                       \-----x-----/                        <--  0.0000  BAM=ARP
                                                                         RXC=NRP
    <--                    0.3396                   -->                  Notches
TRM57971.00: |2+
     / --------------------------------------------- \
    +                                                 +
     \ --------------------------------------------- /
                     \               /
                      \             /
                       \-----x-----/                        <--  0.0000  BAM=ARP
                                                                         RXC=NRP
    <--                    0.3396                   -->                  Notches
TRM55971.00: |2+
     / --------------------------------------------- \
    +                                                 +
     \ --------------------------------------------- /
                     \               /
                      \             /
                       \-----x-----/                        <--  0.0000  BAM=ARP
                                                                         RXC=NRP
    <--                    0.3396                   -->                  Notches

#vim: tabstop=2 expandtab shiftwidth=2 softtabstop=2
