---

# used to determine country name

"New Zealand":
  Latitude: -40.0
  Longitude: 174.0
"Tonga":
  Latitude: -21.2
  Longitude: -175.2
"Samoa":
  Latitude: -13.8
  Longitude: -172.1
"Niue":
  Latitude: -19.0
  Longitude: -169.9

#vim: tabstop=2 expandtab shiftwidth=2 softtabstop=2
