---

PreparedBy: "Elisabetta D'Anastasio"
PrimaryDatacentre: "ftp.geonet.org.nz"
URLForMoreInformation: "www.geonet.org.nz"
ExtraNotes: "additional information and pictures could be\nfound at http://magma.geonet.org.nz/delta/app\nthen search for CGPS mark"

#vim: tabstop=2 expandtab shiftwidth=2 softtabstop=2
