name: go-apps
on:
  push: {}
  release:
    types: [published]
  workflow_dispatch: {}
permissions:
  packages: write
  contents: write
  pull-requests: write
  id-token: write
jobs:
  go-apps:
    uses: GeoNet/Actions/.github/workflows/reusable-go-apps.yml@main
  # TODO add trigger for ac-tools and sit
